[[appendix]]
= Appendix

* goal
    ** topics / -- apply to -- multiple core Spring Framework's modules

[[appendix-spring-properties]]
== Spring Properties

* {spring-framework-api}/core/SpringProperties.html[`SpringProperties`]
    ** := static holder for properties /
        *** control low-level aspects of the Spring Framework
        *** ways to be configured by users
            **** via JVM system properties or
            **** programmatically via the `SpringProperties.setProperty(String key, String value)`
                ***** if the deployment environment disallows custom JVM system properties -> it's the 1! way
            **** `spring.properties` | root of the classpath
                ***** _Example:_ deployed | application's JAR file

.Supported Spring Properties
[cols="1,1"]
|===
| Name | Description

| `spring.aot.enabled`
| == application -- should run with -- AOT generated artifacts

Check

&#160; &#160; - xref:core/aot.adoc[Ahead of Time Optimizations] and

&#160; &#160; - {spring-framework-api}++/aot/AotDetector.html#AOT_ENABLED++[`AotDetector`]

| `spring.beaninfo.ignore`
| if Spring calls JavaBeans `Introspector` -> Spring uses the `Introspector.IGNORE_ALL_BEANINFO` mode


Check {spring-framework-api}++/beans/StandardBeanInfoFactory.html#IGNORE_BEANINFO_PROPERTY_NAME++[`CachedIntrospectionResults`]

| `spring.cache.reactivestreams.ignore`
| Spring's caching infrastructure ignore the presence of Reactive Streams / Reactor's `Mono`/`Flux` in `@Cacheable` method return type declarations

Check {spring-framework-api}++/cache/interceptor/CacheAspectSupport.html#IGNORE_REACTIVESTREAMS_PROPERTY_NAME++[`CacheAspectSupport`]

| `spring.classformat.ignore`
| Spring ignore class format exceptions / unsupported class file versions -- during -- classpath scanning

Check {spring-framework-api}++/context/annotation/ClassPathScanningCandidateComponentProvider.html#IGNORE_CLASSFORMAT_PROPERTY_NAME++[`ClassPathScanningCandidateComponentProvider`]

| `spring.context.checkpoint`
| == common context checkpoint

Check 

&#160; &#160; - xref:integration/checkpoint-restore.adoc#_automatic_checkpointrestore_at_startup[Automatic checkpoint/restore at startup]

&#160; &#160; - {spring-framework-api}++/context/support/DefaultLifecycleProcessor.html#CHECKPOINT_PROPERTY_NAME++[`DefaultLifecycleProcessor`]

| `spring.context.exit`
| once context reaches a specific phase -> terminate the JVM

Check 

&#160; &#160; - xref:integration/checkpoint-restore.adoc#_automatic_checkpointrestore_at_startup[Automatic checkpoint/restore at startup] 

&#160; &#160; - {spring-framework-api}++/context/support/DefaultLifecycleProcessor.html#EXIT_PROPERTY_NAME++[`DefaultLifecycleProcessor`]

| `spring.context.expression.maxLength`
|  maximum length for xref:core/expressions/evaluation.adoc#expressions-parser-configuration[Spring Expression Language]

_Example:_ expressions used in XML bean definitions, `@Value`, ...

| `spring.expression.compiler.mode`
| == mode / compiling expressions for the
xref:core/expressions/evaluation.adoc#expressions-compiler-configuration[Spring Expression Language]

| `spring.getenv.ignore`
| == if a Spring `Environment` property (_Example:_ placeholder on configuration String) is NOT resolvable -> ignore OS environment variables 

Check {spring-framework-api}++/core/env/AbstractEnvironment.html#IGNORE_GETENV_PROPERTY_NAME++[`AbstractEnvironment`]

| `spring.jdbc.getParameterType.ignore`
| == ignore `java.sql.ParameterMetaData.getParameterType` completely

Check xref:data-access/jdbc/advanced.adoc#jdbc-batch-list[Batch Operations with a List of Objects]

| `spring.jndi.ignore`
| == ignore a default JNDI environment

uses: nothing -- is ever to be found for -- JNDI fallback searches -> avoiding the repeated JNDI lookup overhead

Check {spring-framework-api}++/jndi/JndiLocatorDelegate.html#IGNORE_JNDI_PROPERTY_NAME++[`JndiLocatorDelegate`]

| `spring.objenesis.ignore`
| == ignore Objenesis / NOT even attempting to use it

Check {spring-framework-api}++/objenesis/SpringObjenesis.html#IGNORE_OBJENESIS_PROPERTY_NAME++[`SpringObjenesis`]

| `spring.test.aot.processing.failOnError`
| := boolean flag / controls whether errors during AOT processing in _Spring TestContext Framework_  -- should result in -- exception / fails the overall process

Check xref:testing/testcontext-framework/aot.adoc[Ahead of Time Support for Tests]

| `spring.test.constructor.autowire.mode`
| == if `@TestConstructor` is NOT present on a test class -> default _test constructor autowire mode_ 

Check xref:testing/annotations/integration-junit-jupiter.adoc#integration-testing-annotations-testconstructor[Changing the default test constructor autowire mode]

| `spring.test.context.cache.maxSize`
| == maximum size of the context cache in the _Spring TestContext Framework_

Check xref:testing/testcontext-framework/ctx-management/caching.adoc[Context Caching]

| `spring.test.context.failure.threshold`
| == failure threshold / errors attempting to load an `ApplicationContext` in the _Spring TestContext Framework_

Check xref:testing/testcontext-framework/ctx-management/failure-threshold.adoc[Context Failure Threshold]

| `spring.test.enclosing.configuration`
| == if `@NestedTestConfiguration` is NOT present on a test class -> default _enclosing configuration inheritance mode_ 

Check xref:testing/annotations/integration-junit-jupiter.adoc#integration-testing-annotations-nestedtestconfiguration[Changing the default enclosing configuration inheritance mode]

|===
