[[appendix]]
= Appendix

* goal
    ** topics / -- apply to -- multiple core Spring Framework's modules

[[appendix-spring-properties]]
== Spring Properties

* {spring-framework-api}/core/SpringProperties.html[`SpringProperties`]
    ** := static holder for properties /
        *** control low-level aspects of the Spring Framework
        *** ways to be configured by users
            **** via JVM system properties or
            **** programmatically via the `SpringProperties.setProperty(String key, String value)`
                ***** if the deployment environment disallows custom JVM system properties -> it's the 1! way
            **** `spring.properties` | root of the classpath
                ***** _Example:_ deployed | application's JAR file

.Supported Spring Properties
[cols="1,1"]
|===
| Name | Description

| `spring.aot.enabled`
| == application -- should run with -- AOT generated artifacts

Check

&#160; &#160; - xref:core/aot.adoc[Ahead of Time Optimizations] and

&#160; &#160; - {spring-framework-api}++/aot/AotDetector.html#AOT_ENABLED++[`AotDetector`]

| `spring.beaninfo.ignore`
| if Spring calls JavaBeans `Introspector` -> Spring uses the `Introspector.IGNORE_ALL_BEANINFO` mode


Check {spring-framework-api}++/beans/StandardBeanInfoFactory.html#IGNORE_BEANINFO_PROPERTY_NAME++[`CachedIntrospectionResults`]

| `spring.cache.reactivestreams.ignore`
| Spring's caching infrastructure ignore the presence of Reactive Streams / Reactor's `Mono`/`Flux` in `@Cacheable` method return type declarations

Check {spring-framework-api}++/cache/interceptor/CacheAspectSupport.html#IGNORE_REACTIVESTREAMS_PROPERTY_NAME++[`CacheAspectSupport`]

| `spring.classformat.ignore`
| Spring ignore class format exceptions / unsupported class file versions -- during -- classpath scanning

Check {spring-framework-api}++/context/annotation/ClassPathScanningCandidateComponentProvider.html#IGNORE_CLASSFORMAT_PROPERTY_NAME++[`ClassPathScanningCandidateComponentProvider`]

| `spring.context.checkpoint`
| == common context checkpoint

Check 

&#160; &#160; - xref:integration/checkpoint-restore.adoc#_automatic_checkpointrestore_at_startup[Automatic checkpoint/restore at startup]
&#160; &#160; - {spring-framework-api}++/context/support/DefaultLifecycleProcessor.html#CHECKPOINT_PROPERTY_NAME++[`DefaultLifecycleProcessor`]

| `spring.context.exit`
| once context reaches a specific phase -> terminate the JVM

Check 

&#160; &#160; - xref:integration/checkpoint-restore.adoc#_automatic_checkpointrestore_at_startup[Automatic checkpoint/restore at startup] and
&#160; &#160; - {spring-framework-api}++/context/support/DefaultLifecycleProcessor.html#EXIT_PROPERTY_NAME++[`DefaultLifecycleProcessor`]

| `spring.context.expression.maxLength`
|  maximum length for xref:core/expressions/evaluation.adoc#expressions-parser-configuration[Spring Expression Language]

_Example:_ expressions used in XML bean definitions, `@Value`, ...

| `spring.expression.compiler.mode`
| // TODO:The mode to use when compiling expressions for the
xref:core/expressions/evaluation.adoc#expressions-compiler-configuration[Spring Expression Language].

| `spring.getenv.ignore`
| Instructs Spring to ignore operating system environment variables if a Spring
`Environment` property -- for example, a placeholder in a configuration String -- isn't
resolvable otherwise. See
{spring-framework-api}++/core/env/AbstractEnvironment.html#IGNORE_GETENV_PROPERTY_NAME++[`AbstractEnvironment`]
for details.

| `spring.jdbc.getParameterType.ignore`
| Instructs Spring to ignore `java.sql.ParameterMetaData.getParameterType` completely.
See the note in xref:data-access/jdbc/advanced.adoc#jdbc-batch-list[Batch Operations with a List of Objects].

| `spring.jndi.ignore`
| Instructs Spring to ignore a default JNDI environment, as an optimization for scenarios
where nothing is ever to be found for such JNDI fallback searches to begin with, avoiding
the repeated JNDI lookup overhead. See
{spring-framework-api}++/jndi/JndiLocatorDelegate.html#IGNORE_JNDI_PROPERTY_NAME++[`JndiLocatorDelegate`]
for details.

| `spring.objenesis.ignore`
| Instructs Spring to ignore Objenesis, not even attempting to use it. See
{spring-framework-api}++/objenesis/SpringObjenesis.html#IGNORE_OBJENESIS_PROPERTY_NAME++[`SpringObjenesis`]
for details.

| `spring.test.aot.processing.failOnError`
| A boolean flag that controls whether errors encountered during AOT processing in the
_Spring TestContext Framework_ should result in an exception that fails the overall process.
See xref:testing/testcontext-framework/aot.adoc[Ahead of Time Support for Tests].

| `spring.test.constructor.autowire.mode`
| The default _test constructor autowire mode_ to use if `@TestConstructor` is not present
on a test class. See xref:testing/annotations/integration-junit-jupiter.adoc#integration-testing-annotations-testconstructor[Changing the default test constructor autowire mode].

| `spring.test.context.cache.maxSize`
| The maximum size of the context cache in the _Spring TestContext Framework_. See
xref:testing/testcontext-framework/ctx-management/caching.adoc[Context Caching].

| `spring.test.context.failure.threshold`
| The failure threshold for errors encountered while attempting to load an `ApplicationContext`
in the _Spring TestContext Framework_. See
xref:testing/testcontext-framework/ctx-management/failure-threshold.adoc[Context Failure Threshold].

| `spring.test.enclosing.configuration`
| The default _enclosing configuration inheritance mode_ to use if
`@NestedTestConfiguration` is not present on a test class. See
xref:testing/annotations/integration-junit-jupiter.adoc#integration-testing-annotations-nestedtestconfiguration[Changing the default enclosing configuration inheritance mode].

|===
