[[overview]]
= Spring Framework Overview
:docinfo1:

* Spring
    ** makes it easy to create Java enterprise applications
    ** support for
        *** Groovy
        *** Kotlin
    ** let to create many kinds of architectures
    ** Spring Framework 6.0+ -> require Java 17+
    ** use cases
        *** large enterprise, applications
        *** 1! jar / server embedded (_Example:_ | cloud environment)
        *** standalone applications / NOT require servers ( _Example:_ batch or integration workloads)
    ** open source /
        *** large and active community

[[overview-spring]]
== What We Mean by "Spring"

* Spring meaning -- based on the -- context
    ** Spring Framework project itself
        *** origin of ALL
        *** this documentation
    ** entire family of Spring projects
* Spring Framework -- is divided into -- modules
    ** main modules == "spring-core" + configuration model + DI mechanism
    ** support for different
        *** application architectures -- including messaging --
        *** transactional data
        *** persistence
        *** web -- "spring-web" --
                **** "spring-webmvc"
                **** "spring-webflux"
    ** Spring's framework jars 
       *** allow
         **** deployment | JDK 9's module path (== link:https://openjdk.org/projects/jigsaw/[Jigsaw])
         **** + JDK 8 or 9+ -- keep on -- working fine | classpath 
       *** v5 -- come with -- "Automatic-Module-Name" manifest entries / 
         **** stable language-level module names ("spring.core", "spring.context", etc.) -- independent from -- jar artifact names ( "spring-core" and "spring-context")

[[overview-history]]
== History of Spring and the Spring Framework

* Root cause of it's origin
   ** complexity of the early https://en.wikipedia.org/wiki/Java_Platform,_Enterprise_Edition[J2EE] specifications
* vs Java EE or its modern-day successor Jakarta EE
   ** complementary
   ** Spring programming model 
      *** does NOT embrace ALL the Jakarta EE platform specification
      *** integrates with carefully SELECTED individual Java EE specifications
         **** Servlet API ({JSR}340[JSR 340])
         **** WebSocket API ({JSR}356[JSR 356])
         **** Concurrency Utilities ({JSR}236[JSR 236])
         **** JSON Binding API ({JSR}367[JSR 367])
         **** Bean Validation ({JSR}303[JSR 303])
         **** JPA ({JSR}338[JSR 338])
         **** JMS ({JSR}914[JSR 914])
         **** JTA/JCA setups | transaction coordination
      *** supports / instead of  Spring-specific mechanisms
         **** Dependency Injection ({JSR}330[JSR 330])
         **** Common Annotations ({JSR}250[JSR 250]) 
      *** From Spring Framework 6.0 -> upgraded to Jakarta EE 9
         **** Spring -- is prepared to provide out-of-the-box -- support for the further evolution of the Jakarta EE APIs
         **** fully compatible with
            ***** web servers
               ****** Tomcat 10.1
               ****** Jetty 11
               ****** Undertow 2.3
            ***** Hibernate ORM 6.1
* uses of Java/Jakarta EE & Spring
   ** originally
      *** applications / be deployed | an application server
   ** nowadays
      *** applications / 
         **** Servlet container embedded
         **** cloud-friendly way
         **** NOT use the Servlet API & run | servers / != Servlet containers
            ***** == Webflux applications
* There are many Spring projects -- Check {spring-site-projects}[spring.io/projects] --
   ** Spring Boot,
   ** Spring Security,
   ** Spring Data,
   ** Spring Cloud,
   ** Spring Batch,
   ** ..

[[overview-philosophy]]
== Design Philosophy

* TODO:
When you learn about a framework, it’s important to know not only what it does but what
principles it follows. Here are the guiding principles of the Spring Framework:

* Provide choice at every level. Spring lets you defer design decisions as late as possible.
For example, you can switch persistence providers through configuration without changing
your code. The same is true for many other infrastructure concerns and integration with
third-party APIs.
* Accommodate diverse perspectives. Spring embraces flexibility and is not opinionated
about how things should be done. It supports a wide range of application needs with
different perspectives.
* Maintain strong backward compatibility. Spring’s evolution has been carefully managed
to force few breaking changes between versions. Spring supports a carefully chosen range
of JDK versions and third-party libraries to facilitate maintenance of applications and
libraries that depend on Spring.
* Care about API design. The Spring team puts a lot of thought and time into making APIs
that are intuitive and that hold up across many versions and many years.
* Set high standards for code quality. The Spring Framework puts a strong emphasis on
meaningful, current, and accurate javadoc. It is one of very few projects that can claim
clean code structure with  no circular dependencies between packages.




[[overview-feedback]]
== Feedback and Contributions

For how-to questions or diagnosing or debugging issues, we suggest using Stack Overflow. Click
{stackoverflow-spring-tag}+or+spring-mvc+or+spring-aop+or+spring-jdbc+or+spring-r2dbc+or+spring-transactions+or+spring-annotations+or+spring-jms+or+spring-el+or+spring-test+or+spring+or+spring-orm+or+spring-jmx+or+spring-cache+or+spring-webflux+or+spring-rsocket?tab=Newest[here]
for a list of the suggested tags to use on Stack Overflow. If you're fairly certain that
there is a problem in the Spring Framework or would like to suggest a feature, please use
the {spring-framework-issues}[GitHub Issues].

If you have a solution in mind or a suggested fix, you can submit a pull request on
{spring-framework-github}[Github]. However, please keep in mind
that, for all but the most trivial issues, we expect a ticket to be filed in the issue
tracker, where discussions take place and leave a record for future reference.

For more details see the guidelines at the {spring-framework-code}/CONTRIBUTING.md[CONTRIBUTING],
top-level project page.




[[overview-getting-started]]
== Getting Started

If you are just getting started with Spring, you may want to begin using the Spring
Framework by creating a {spring-site-projects}/spring-boot/[Spring Boot]-based
application. Spring Boot provides a quick (and opinionated) way to create a
production-ready Spring-based application. It is based on the Spring Framework, favors
convention over configuration, and is designed to get you up and running as quickly
as possible.

You can use https://start.spring.io/[start.spring.io] to generate a basic project or follow
one of the {spring-site-guides}["Getting Started" guides], such as
{spring-site-guides}/gs/rest-service/[Getting Started Building a RESTful Web Service].
As well as being easier to digest, these guides are very task focused, and most of them
are based on Spring Boot. They also cover other projects from the Spring portfolio that
you might want to consider when solving a particular problem.
