[[spring-mvc-test-client]]
= Testing Client Applications

* == client-side tests / test code -- internally uses -- `RestTemplate`
* goal
    ** declare expected requests
    ** provide "`stub`" responses
    ** focus on testing the code | isolation (== WITHOUT running a server)
* `MockRestServiceServer`
    ** == central class for client-side REST tests
    ** `RestTemplate`
        *** used as usual
        *** `ClientHttpRequestFactory` implementation / can be configured | `RestTemplate` &
bind it -- to a -- `MockMvc` instance
            **** -> actual server-side logic / WITHOUT running a server
    ** request are expected
        *** by default, -- based on -- expectations declared
        *** if you set `ignoreExpectOrder` | building the server -> ALL expectations are checked -- to find a -- match / given request == requests are allowed | ANY order
            **** JUST applied | first HTTP request
* _Example:_

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	RestTemplate restTemplate = new RestTemplate();

	MockRestServiceServer mockServer = MockRestServiceServer.bindTo(restTemplate).build();
    // expect a request to `/greeting` & want to return 200 response with `text/plain` content
	mockServer.expect(requestTo("/greeting")).andRespond(withSuccess());

	// Test code that uses the above RestTemplate ...

	mockServer.verify();
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	val restTemplate = RestTemplate()

	val mockServer = MockRestServiceServer.bindTo(restTemplate).build()
    // expect a request to `/greeting` & want to return 200 response with `text/plain` content
	mockServer.expect(requestTo("/greeting")).andRespond(withSuccess())

	// Test code that uses the above RestTemplate ...

	mockServer.verify()
----
======

* _Example:_ specify `ignoreExpectOrder`

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	server = MockRestServiceServer.bindTo(restTemplate).ignoreExpectOrder(true).build();
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	server = MockRestServiceServer.bindTo(restTemplate).ignoreExpectOrder(true).build()
----
======

* _Example:_ specify range of expectations / HTTP request -- via -- `expect(ExpectedCount count, RequestMatcher matcher)`
    ** `ignoreExpectOrder` is NOT set == default == requests are expected in order of declaration
        *** order applies ONLY | first of any expected request
[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	RestTemplate restTemplate = new RestTemplate();

	MockRestServiceServer mockServer = MockRestServiceServer.bindTo(restTemplate).build();
    // expected order
    // 1. request to
    // 2. another request to "/something" or request to "/somewhere"
    // 3. another request to whatever
	mockServer.expect(times(2), requestTo("/something")).andRespond(withSuccess());
	mockServer.expect(times(3), requestTo("/somewhere")).andRespond(withSuccess());

	// ...

	mockServer.verify();
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	val restTemplate = RestTemplate()

	val mockServer = MockRestServiceServer.bindTo(restTemplate).build()
    // expected order
    // 1. request to
    // 2. another request to "/something" or request to "/somewhere"
    // 3. another request to whatever
	mockServer.expect(times(2), requestTo("/something")).andRespond(withSuccess())
	mockServer.expect(times(3), requestTo("/somewhere")).andRespond(withSuccess())

	// ...

	mockServer.verify()
----
======

* _Example:_ `ClientHttpRequestFactory` implementation | `RestTemplate`

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	MockMvc mockMvc = MockMvcBuilders.webAppContextSetup(this.wac).build();
	this.restTemplate = new RestTemplate(new MockMvcClientHttpRequestFactory(mockMvc));

	// Test code that uses the above RestTemplate ...
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	val mockMvc = MockMvcBuilders.webAppContextSetup(this.wac).build()
	restTemplate = RestTemplate(MockMvcClientHttpRequestFactory(mockMvc))

	// Test code that uses the above RestTemplate ...
----
======

* `ExecutingResponseCreator`
    ** perform an actual call -- to a -- remote service (!= mocking the response)
    ** _Example:_

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	RestTemplate restTemplate = new RestTemplate();

	// Create ExecutingResponseCreator with the original request factory (== `ClientHttpRequestFactory`)
	ExecutingResponseCreator withActualResponse = new ExecutingResponseCreator(restTemplate.getRequestFactory());

	MockRestServiceServer mockServer = MockRestServiceServer.bindTo(restTemplate).build();
	mockServer.expect(requestTo("/profile")).andRespond(withSuccess()); // NO actual request will be executed
	mockServer.expect(requestTo("/quoteOfTheDay")).andRespond(withActualResponse); // real call == -- through -- `ClientHttpRequestFactory`

	// Test code that uses the above RestTemplate ...

	mockServer.verify();
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	val restTemplate = RestTemplate()

	// Create ExecutingResponseCreator with the original request factory (== `ClientHttpRequestFactory`)
	val withActualResponse = new ExecutingResponseCreator(restTemplate.getRequestFactory())

	val mockServer = MockRestServiceServer.bindTo(restTemplate).build()
	mockServer.expect(requestTo("/profile")).andRespond(withSuccess()) // NO actual request will be executed
	mockServer.expect(requestTo("/quoteOfTheDay")).andRespond(withActualResponse) // real call == -- through -- `ClientHttpRequestFactory`

	// Test code that uses the above RestTemplate ...

	mockServer.verify()
----
======

[[spring-mvc-test-client-static-imports]]
== Static Imports

* static imports / -- found by -- `MockRest*`
    ** Eclipse users -- should add -- `MockRestRequestMatchers.{asterisk}` and `MockRestResponseCreators.{asterisk}` as
"`favorite static members`" | Eclipse preferences (Java -> Editor -> Content
Assist -> Favorites)
        *** -> content assist | after typing the first character

[[spring-mvc-test-client-resources]]
== Further Examples of Client-side REST Tests

* Check {spring-framework-code}/spring-test/src/test/java/org/springframework/test/web/client/samples[example
tests]
