[[web-integration]]
= Other Web Frameworks

* goal
	** Spring's integration -- with -- third-party web frameworks / allows
		*** looking up beans simpler 
		*** using DI | their controllers
* Spring enable choose ANY
	** architecture,
	** technology,
		*** _Example:_ | web area with (xref:web/webmvc.adoc#mvc[Spring MVC] & xref:web/webflux.adoc#webflux[Spring WebFlux])
	** methodology

[[web-integration-common]]
== Common Configuration

* common Spring configuration
	** layered architecture / web layer
		*** one of many layers
		*** == entry points | server-side application / -- delegates, to satisfy business-specific, to -- service objects (facades) /
			**** defined | service layer
			**** presentation-technology agnostic
			**** vs other business-specific objects, data-access objects -- exist -- | distinct "business context"
* goal
	** configure a Spring container (`WebApplicationContext`) / contains ALL of the 'business beans' | your application
		*** == 👁️ | your web application´s standard Jakarta EE servlet `web.xml` 👁️
			**** declare {spring-framework-api}/web/context/ContextLoaderListener.html[`ContextLoaderListener`] 

	[source,xml,indent=0,subs="verbatim,quotes"]
	----
		<listener>
			<listener-class>org.springframework.web.context.ContextLoaderListener</listener-class>
		</listener>
	----

			**** add a `contextConfigLocation` as `<context-param/>` / -- defines -- set of Spring XML configuration files to load
				***** if you do NOT add it -> `ContextLoaderListener` looks for the file `/WEB-INF/applicationContext.xml` to load 

	[source,xml,indent=0,subs="verbatim,quotes"]
	----
		<context-param>
			<param-name>contextConfigLocation</param-name>
			<param-value>/WEB-INF/applicationContext*.xml</param-value>
		</context-param>
	----

	** once the context files are loaded -> Spring creates a {spring-framework-api}/web/context/WebApplicationContext.html[`WebApplicationContext`] object
		*** -- based on the -- bean definitions
		*** stores it | web application's `ServletContext`

* ALL Java web frameworks -- are built -- | Servlet API
	** _Example:_ get access to -- this "business context" `ApplicationContext` / -- created by the -- `ContextLoaderListener`

[source,java,indent=0,subs="verbatim,quotes"]
----
	WebApplicationContext ctx = WebApplicationContextUtils.getWebApplicationContext(servletContext);
----

* {spring-framework-api}/web/context/support/WebApplicationContextUtils.html[`WebApplicationContextUtils`]
	** := class / 
		*** `getWebApplicationContext()`
			**** NO need to remember the name of the `ServletContext`
			**** if an object does NOT exist | `WebApplicationContext.ROOT_WEB_APPLICATION_CONTEXT_ATTRIBUTE` -> returns `null` 
		*** `getRequiredWebApplicationContext()`
			**** if `ApplicationContext` is missing ->  throws an exception
			**** vs `getWebApplicationContext()`
				***** recommended `getRequiredWebApplicationContext()`
* once you have a reference to the `WebApplicationContext` -> you can retrieve beans -- by -- their
	** name
		*** then, you -- cast to -- one of their implemented interfaces
	** type


[[jsf]]
== JSF

// TODO:
JavaServer Faces (JSF) is the JCP's standard component-based, event-driven web
user interface framework. It is an official part of the Jakarta EE umbrella but also
individually usable, e.g. through embedding Mojarra or MyFaces within Tomcat.

Please note that recent versions of JSF became closely tied to CDI infrastructure
in application servers, with some new JSF functionality only working in such an
environment. Spring's JSF support is not actively evolved anymore and primarily
exists for migration purposes when modernizing older JSF-based applications.

The key element in Spring's JSF integration is the JSF `ELResolver` mechanism.



[[jsf-springbeanfaceselresolver]]
=== Spring Bean Resolver

`SpringBeanFacesELResolver` is a JSF compliant `ELResolver` implementation,
integrating with the standard Unified EL as used by JSF and JSP. It delegates to
Spring's "business context" `WebApplicationContext` first and then to the
default resolver of the underlying JSF implementation.

Configuration-wise, you can define `SpringBeanFacesELResolver` in your JSF
`faces-context.xml` file, as the following example shows:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<faces-config>
		<application>
			<el-resolver>org.springframework.web.jsf.el.SpringBeanFacesELResolver</el-resolver>
			...
		</application>
	</faces-config>
----



[[jsf-facescontextutils]]
=== Using `FacesContextUtils`

A custom `ELResolver` works well when mapping your properties to beans in
`faces-config.xml`, but, at times, you may need to explicitly grab a bean.
The {spring-framework-api}/web/jsf/FacesContextUtils.html[`FacesContextUtils`]
class makes this easy. It is similar to `WebApplicationContextUtils`, except that
it takes a `FacesContext` parameter rather than a `ServletContext` parameter.

The following example shows how to use `FacesContextUtils`:

[source,java,indent=0,subs="verbatim,quotes"]
----
	ApplicationContext ctx = FacesContextUtils.getWebApplicationContext(FacesContext.getCurrentInstance());
----




[[struts]]
== Apache Struts

Invented by Craig McClanahan, https://struts.apache.org[Struts] is an open-source project
hosted by the Apache Software Foundation. Struts 1.x greatly simplified the
JSP/Servlet programming paradigm and won over many developers who were using proprietary
frameworks. It simplified the programming model; it was open source; and it had a large
community, which let the project grow and become popular among Java web developers.

As a successor to the original Struts 1.x, check out Struts 2.x or more recent versions
as well as the Struts-provided
https://struts.apache.org/plugins/spring/[Spring Plugin] for built-in Spring integration.




[[tapestry]]
== Apache Tapestry

https://tapestry.apache.org/[Tapestry] is a "Component oriented framework for creating
dynamic, robust, highly scalable web applications in Java."

While Spring has its own xref:web/webmvc.adoc#mvc[powerful web layer], there are a number of unique
advantages to building an enterprise Java application by using a combination of Tapestry
for the web user interface and the Spring container for the lower layers.

For more information, see Tapestry's dedicated
https://tapestry.apache.org/integrating-with-spring-framework.html[integration module for Spring].




[[web-integration-resources]]
== Further Resources

The following links go to further resources about the various web frameworks described in
this chapter.

* The https://www.oracle.com/java/technologies/javaserverfaces.html[JSF] homepage
* The https://struts.apache.org/[Struts] homepage
* The https://tapestry.apache.org/[Tapestry] homepage
