[[mockmvc-server-defining-expectations]]
= Defining Expectations

* `.andExpect(..)` | after performing a request
    ** >=1 can be added
    ** allows
        *** defining expectations
            **** if an expectation fails -> next expectations will NOT be asserted
    ** _Example:_

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	// static import of MockMvcRequestBuilders.* and MockMvcResultMatchers.*

	mockMvc.perform(get("/accounts/1")).andExpect(status().isOk());
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	import org.springframework.test.web.servlet.get

	mockMvc.get("/accounts/1").andExpect {
		status { isOk() }
	}
----
======

* `.andExpectAll(..)` | after performing a request
    ** allows
        *** defining multiple expectations
    ** vs `andExpect(..)`
        *** ALL supplied expectations will be asserted
        *** ALL failures will be tracked and reported
    ** _Example:_

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	// static import of MockMvcRequestBuilders.* and MockMvcResultMatchers.*

	mockMvc.perform(get("/accounts/1")).andExpectAll(
		status().isOk(),
		content().contentType("application/json;charset=UTF-8"));
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	import org.springframework.test.web.servlet.get

	mockMvc.get("/accounts/1").andExpectAll {
		status { isOk() }
		content { contentType(APPLICATION_JSON) }
	}
----
======

* `MockMvcResultMatchers.*`
    ** provides expectations / some of them can be nested

* expectations categories
    ** assertions / verify properties of the response
        *** _Example:_ response status, headers, and content
        *** most important results / assert
    ** assertions / goes beyond the response
        *** inspect Spring MVC specific aspects
            **** _Example:_ controller method / processed the request, an exception was raised and handled, content of the model is, view was selected, flash attributes were added
        *** inspect Servlet specific aspects
            **** _Example:_ request and session attributes
* _Example:_ assert / binding or validation failed

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	mockMvc.perform(post("/persons"))
		.andExpect(status().isOk())
		.andExpect(model().attributeHasErrors("person"));
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	import org.springframework.test.web.servlet.post

	mockMvc.post("/persons").andExpect {
		status { isOk() }
		model {
			attributeHasErrors("person")
		}
	}
----
======

* `static ...MockMvcResultHandlers.print`
    ** uses
        *** writing tests
    ** allows
        *** if request processing does NOT cause an unhandled exception -> dump the results of the performed request -- to -- `System.out`
    ** variants
        *** `print(OutputStream)`
        *** `print(Writer)`
            **** _Example:_ `print(myWriter)` -- prints the result data to a -- custom writer
            **** _Example:_ `print(System.err)` -- prints the result data to -- `System.err`
    ** alternative
        *** `log()`
            **** result data is logged as `DEBUG` | `org.springframework.test.web.servlet.result`
                ***** != printed
    ** _Example:_

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	mockMvc.perform(post("/persons"))
		.andDo(print())
		.andExpect(status().isOk())
		.andExpect(model().attributeHasErrors("person"));
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	import org.springframework.test.web.servlet.post

	mockMvc.post("/persons").andDo {
			print()
		}.andExpect {
			status { isOk() }
			model {
				attributeHasErrors("person")
			}
		}
----
======


* `.andReturn()` | after ALL other expectations
    ** allows
        *** getting direct access to the result
        *** verifying something / can NOT be verified otherwise
    ** _Example:_

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	MvcResult mvcResult = mockMvc.perform(post("/persons")).andExpect(status().isOk()).andReturn();
	// ...
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	var mvcResult = mockMvc.post("/persons").andExpect { status { isOk() } }.andReturn()
	// ...
----
======


* if all tests repeat the same expectations -> you can set up COMMON expectations | building the `MockMvc` instance
    ** common expectations are ALWAYS applied & NOT possible to override
        *** ⚠️if you want to change -> you need to create a separate `MockMvc` instance ⚠️

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	standaloneSetup(new SimpleController())
		.alwaysExpect(status().isOk())
		.alwaysExpect(content().contentType("application/json;charset=UTF-8"))
		.build()
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	// Not possible in Kotlin until {kotlin-issues}/KT-22208 is fixed
----
======


* TODO:
When a JSON response content contains hypermedia links created with
{spring-github-org}/spring-hateoas[Spring HATEOAS], you can verify the
resulting links by using JsonPath expressions, as the following example shows:

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	mockMvc.perform(get("/people").accept(MediaType.APPLICATION_JSON))
		.andExpect(jsonPath("$.links[?(@.rel == 'self')].href").value("http://localhost:8080/people"));
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	mockMvc.get("/people") {
		accept(MediaType.APPLICATION_JSON)
	}.andExpect {
		jsonPath("$.links[?(@.rel == 'self')].href") {
			value("http://localhost:8080/people")
		}
	}
----
======

When XML response content contains hypermedia links created with
{spring-github-org}/spring-hateoas[Spring HATEOAS], you can verify the
resulting links by using XPath expressions:

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	Map<String, String> ns = Collections.singletonMap("ns", "http://www.w3.org/2005/Atom");
	mockMvc.perform(get("/handle").accept(MediaType.APPLICATION_XML))
		.andExpect(xpath("/person/ns:link[@rel='self']/@href", ns).string("http://localhost:8080/people"));
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	val ns = mapOf("ns" to "http://www.w3.org/2005/Atom")
	mockMvc.get("/handle") {
		accept(MediaType.APPLICATION_XML)
	}.andExpect {
		xpath("/person/ns:link[@rel='self']/@href", ns) {
			string("http://localhost:8080/people")
		}
	}
----
======

