[[mockmvc-setup]]
= Configuring MockMvc

* ways to set up MockMvc
    ** point directly to the controllers & programmatically configure Spring MVC infrastructure
        *** _Example:_

    [tabs]
    ======
    Java::
    +
    [source,java,indent=0,subs="verbatim,quotes",role="primary"]
    ----
        class MyWebTests {

            MockMvc mockMvc;

            @BeforeEach
            void setup() {
                // set up MockMvc / test a specific controller
                this.mockMvc = MockMvcBuilders.standaloneSetup(new AccountController()).build();

            }

            // ...

        }
    ----

    Kotlin::
    +
    [source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
    ----
        class MyWebTests {

            lateinit var mockMvc : MockMvc

            @BeforeEach
            fun setup() {
                // set up MockMvc / test a specific controller
                mockMvc = MockMvcBuilders.standaloneSetup(AccountController()).build()
            }

            // ...

        }
    ----
    ======

    ** point to Spring configuration / Spring MVC & controller infrastructure in it
        *** _Example:_

    [tabs]
    ======
    Java::
    +
    [source,java,indent=0,subs="verbatim,quotes",role="primary"]
    ----
        @SpringJUnitWebConfig(locations = "my-servlet-context.xml")
        class MyWebTests {

            MockMvc mockMvc;

            @BeforeEach
            void setup(WebApplicationContext wac) {
                // set up MockMvc -- via -- Spring configuration
                this.mockMvc = MockMvcBuilders.webAppContextSetup(wac).build();
                // ALSO valid, testing -- via -- xref:testing/webtestclient.adoc#webtestclient-context-config[WebTestClient]
            }

            // ...

        }
    ----

    Kotlin::
    +
    [source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
    ----
        @SpringJUnitWebConfig(locations = ["my-servlet-context.xml"])
        class MyWebTests {

            lateinit var mockMvc: MockMvc

            @BeforeEach
            fun setup(wac: WebApplicationContext) {
                // set up MockMvc -- via -- Spring configuration
                mockMvc = MockMvcBuilders.webAppContextSetup(wac).build()
            }

            // ...

        }
    ----
    ======

* if you want to compare 2 previous ways -> check xref:testing/mockmvc/setup-options.adoc[Setup Options]
