[[mvc-redirecting-passing-data]]
= Redirect Attributes

* ðŸ‘ï¸ALL model attributes -- are exposed, by default, as -- URI template variables | redirect URL ðŸ‘ï¸
    ** check redirectURL [[viewresolver.mvc-redirecting-redirect-prefix]]
    ** ðŸ‘ï¸ NOT need to explicitly add through `Model` or `RedirectAttributes` ðŸ‘ï¸
* remaining attributes,
    ** := attributes / are
        *** primitive types or
        *** collections or arrays of primitive types
    ** -- are ðŸ‘ï¸ automatically appended as -- query parameters ðŸ‘ï¸
        *** uses
            **** model instance / prepared specifically for the redirect
        *** if the model | annotated controllers -- contain -- additional attributes added for rendering purposes (_Example:_ drop-down field values) & want to avoid appearing in the URL ->

            @RequestMapping(RedirectAttributes=attributesToMakeAvailableToRedirectView...)

        *** way to avoid it

            RequestMappingHandlerAdapter.ignoreDefaultModelOnRedirect=true

* _Example:_ of `redirect:`

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	@PostMapping("/files/{path}")
	public String upload(...) {
		// ...
		return "redirect:files/{path}";
	}
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	@PostMapping("/files/{path}")
	fun upload(...): String {
		// ...
		return "redirect:files/{path}"
	}
----
======

* Check xref:web/webmvc/mvc-controller/ann-methods/flash-attributes.adoc[Flash Attributes]
