[[beans-java-basic-concepts]]
= Basic Concepts: `@Bean` and `@Configuration`

The central artifacts in Spring's Java configuration support are
`@Configuration`-annotated classes and `@Bean`-annotated methods.

The `@Bean` annotation is used to indicate that a method instantiates, configures, and
initializes a new object to be managed by the Spring IoC container. For those familiar
with Spring's `<beans/>` XML configuration, the `@Bean` annotation plays the same role as
the `<bean/>` element. You can use `@Bean`-annotated methods with any Spring
`@Component`. However, they are most often used with `@Configuration` beans.

Annotating a class with `@Configuration` indicates that its primary purpose is as a
source of bean definitions. Furthermore, `@Configuration` classes let inter-bean
dependencies be defined by calling other `@Bean` methods in the same class.
The simplest possible `@Configuration` class reads as follows:

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	@Configuration
	public class AppConfig {

		@Bean
		public MyServiceImpl myService() {
			return new MyServiceImpl();
		}
	}
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	@Configuration
	class AppConfig {

		@Bean
		fun myService(): MyServiceImpl {
			return MyServiceImpl()
		}
	}
----
======

The preceding `AppConfig` class is equivalent to the following Spring `<beans/>` XML:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<beans>
		<bean id="myService" class="com.acme.services.MyServiceImpl"/>
	</beans>
----

## @Configuration classes with OR without local calls between @Bean methods?

* `@Bean` methods | `@Configuration` classes
    ** Common scenario
    ** allows
        *** full configuration class
        *** cross-method references -- get redirected to -- container's lifecycle management
                **** cross-method references == bean1Method -- reference to -- bean2Method
                **** -> the same `@Bean` method -- is prevented from accidentally being invoked through a -- regular Java method call
                **** reduce subtle bugs / hard to track down

* If `@Bean` methods | classes NOT annotated with `@Configuration` OR `@Configuration(proxyBeanMethods=false)` ->  beans are processed as a "lite" mode
    ** == `@Bean` methods == general-purpose factory method / NO special runtime processing ( == NO CGLIB subclass generated for it)
    ** -> a Java call to such method, ⚠️ NOT get intercepted by the container ⚠️
        *** == regular method call
                **** == new instance created / every time
                *** 👁️ NOT reusing an existing singleton (or scoped) instance / bean 👁️
    ** bean1 -- does NOT have a dependency with -- bean2
        *** == bean1 -- does NOT need to invoke -- bean2's methods
        *** beans -- act on -- their containing component's fields & arguments / a factory method may declare
