[[integration-testing-annotations-meta]]
= Meta-Annotation Support for Testing

* 👁️ most test-related annotations -- can be used as -- xref:core/beans/classpath-scanning.adoc#beans-meta-annotations[meta-annotations] 👁️
    ** -> allows
        *** creating custom composed annotations &
        *** reducing configuration duplication -- across a -- test suite

* allowed meta-annotation / can be used | xref:testing/testcontext-framework.adoc[TestContext framework]
    ** `@BootstrapWith`
    ** `@ContextConfiguration`
    ** `@ContextHierarchy`
    ** `@ContextCustomizerFactories`
    ** `@ActiveProfiles`
    ** `@TestPropertySource`
    ** `@DirtiesContext`
    ** `@WebAppConfiguration`
    ** `@TestExecutionListeners`
    ** `@Transactional`
    ** `@BeforeTransaction`
    ** `@AfterTransaction`
    ** `@Commit`
    ** `@Rollback`
    ** `@Sql`
    ** `@SqlConfig`
    ** `@SqlMergeMode`
    ** `@SqlGroup`
    ** `@Repeat` _(ONLY | JUnit 4)_
    ** `@Timed` _(ONLY | JUnit 4)_
    ** `@IfProfileValue` _(ONLY | JUnit 4)_
    ** `@ProfileValueSourceConfiguration` _(ONLY | JUnit 4)_
    ** `@SpringJUnitConfig` _(ONLY | JUnit Jupiter)_
    ** `@SpringJUnitWebConfig` _(ONLY | JUnit Jupiter)_
    ** `@TestConstructor` _(ONLY | JUnit Jupiter)_
    ** `@NestedTestConfiguration` _(ONLY | JUnit Jupiter)_
    ** `@EnabledIf` _(ONLY | JUnit Jupiter)_
    ** `@DisabledIf` _(ONLY | JUnit Jupiter)_

* _Example:_ let's have

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	@RunWith(SpringRunner.class)
	@ContextConfiguration({"/app-config.xml", "/test-data-access-config.xml"})
	@ActiveProfiles("dev")
	@Transactional
	public class OrderRepositoryTests { }

	@RunWith(SpringRunner.class)
	@ContextConfiguration({"/app-config.xml", "/test-data-access-config.xml"})
	@ActiveProfiles("dev")
	@Transactional
	public class UserRepositoryTests { }
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	@RunWith(SpringRunner::class)
	@ContextConfiguration("/app-config.xml", "/test-data-access-config.xml")
	@ActiveProfiles("dev")
	@Transactional
	class OrderRepositoryTests { }

	@RunWith(SpringRunner::class)
	@ContextConfiguration("/app-config.xml", "/test-data-access-config.xml")
	@ActiveProfiles("dev")
	@Transactional
	class UserRepositoryTests { }
----
======

If we are repeating the preceding configuration | our JUnit 4-based test suite -- via introducing a custom composed annotation / centralizes the common test configuration -> we can reduce the duplication

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	@Target(ElementType.TYPE)
	@Retention(RetentionPolicy.RUNTIME)
	@ContextConfiguration({"/app-config.xml", "/test-data-access-config.xml"})
	@ActiveProfiles("dev")
	@Transactional
	public @interface TransactionalDevTestConfig { }
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	@Target(AnnotationTarget.TYPE)
	@Retention(AnnotationRetention.RUNTIME)
	@ContextConfiguration("/app-config.xml", "/test-data-access-config.xml")
	@ActiveProfiles("dev")
	@Transactional
	annotation class TransactionalDevTestConfig { }
----
======

-> we can use our `@TransactionalDevTestConfig` annotation | individual JUnit 4 based test classes

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	@RunWith(SpringRunner.class)
	@TransactionalDevTestConfig
	public class OrderRepositoryTests { }

	@RunWith(SpringRunner.class)
	@TransactionalDevTestConfig
	public class UserRepositoryTests { }
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	@RunWith(SpringRunner::class)
	@TransactionalDevTestConfig
	class OrderRepositoryTests

	@RunWith(SpringRunner::class)
	@TransactionalDevTestConfig
	class UserRepositoryTests
----
======

* _Example2:_ if we use JUnit Jupiter -> we can reduce code duplication even further

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	@ExtendWith(SpringExtension.class)
	@ContextConfiguration({"/app-config.xml", "/test-data-access-config.xml"})
	@ActiveProfiles("dev")
	@Transactional
	class OrderRepositoryTests { }

	@ExtendWith(SpringExtension.class)
	@ContextConfiguration({"/app-config.xml", "/test-data-access-config.xml"})
	@ActiveProfiles("dev")
	@Transactional
	class UserRepositoryTests { }
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	@ExtendWith(SpringExtension::class)
	@ContextConfiguration("/app-config.xml", "/test-data-access-config.xml")
	@ActiveProfiles("dev")
	@Transactional
	class OrderRepositoryTests { }

	@ExtendWith(SpringExtension::class)
	@ContextConfiguration("/app-config.xml", "/test-data-access-config.xml")
	@ActiveProfiles("dev")
	@Transactional
	class UserRepositoryTests { }
----
======

If we are repeating the preceding configuration | our JUnit Jupiter-based test suite -- via introducing a custom composed annotation / centralizes the common test configuration -> we can reduce the duplication

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	@Target(ElementType.TYPE)
	@Retention(RetentionPolicy.RUNTIME)
	@ExtendWith(SpringExtension.class)
	@ContextConfiguration({"/app-config.xml", "/test-data-access-config.xml"})
	@ActiveProfiles("dev")
	@Transactional
	public @interface TransactionalDevTestConfig { }
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	@Target(AnnotationTarget.TYPE)
	@Retention(AnnotationRetention.RUNTIME)
	@ExtendWith(SpringExtension::class)
	@ContextConfiguration("/app-config.xml", "/test-data-access-config.xml")
	@ActiveProfiles("dev")
	@Transactional
	annotation class TransactionalDevTestConfig { }
----
======

-> we can use our `@TransactionalDevTestConfig` annotation | individual JUnit Jupiter based test classes


[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	@TransactionalDevTestConfig
	class OrderRepositoryTests { }

	@TransactionalDevTestConfig
	class UserRepositoryTests { }
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	@TransactionalDevTestConfig
	class OrderRepositoryTests { }

	@TransactionalDevTestConfig
	class UserRepositoryTests { }
----
======

* _Example3:_ composed annotation / combines `@Test` + `@Tag` + `@Transactional` | 👁️test method level 👁️

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	@Target(ElementType.METHOD)
	@Retention(RetentionPolicy.RUNTIME)
	@Transactional
	@Tag("integration-test") // org.junit.jupiter.api.Tag
	@Test // org.junit.jupiter.api.Test
	public @interface TransactionalIntegrationTest { }
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	@Target(AnnotationTarget.TYPE)
	@Retention(AnnotationRetention.RUNTIME)
	@Transactional
	@Tag("integration-test") // org.junit.jupiter.api.Tag
	@Test // org.junit.jupiter.api.Test
	annotation class TransactionalIntegrationTest { }
----
======

use our custom `@TransactionalIntegrationTest`

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	@TransactionalIntegrationTest
	void saveOrder() { }

	@TransactionalIntegrationTest
	void deleteOrder() { }
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	@TransactionalIntegrationTest
	fun saveOrder() { }

	@TransactionalIntegrationTest
	fun deleteOrder() { }
----
======

* Check {spring-framework-wiki}/Spring-Annotation-Programming-Model[Spring Annotation Programming Model] wiki page.
