[[testcontext-aot]]
= Ahead of Time -- Support for -- Tests

* goal
  ** Spring's Ahead of Time (AOT) support -- via, Spring TestContext Framework, for -- integration tests

* testing support -- extends Spring's xref:core/aot.adoc[core AOT support] /  following features
  ** Build-time detection of ALL integration tests | current project
    *** load an `ApplicationContext` -- via -- TestContext framework
    *** explicit support -- for -- test classes / based on JUnit Jupiter & JUnit 4
    *** implicit support -- for -- TestNG & other testing frameworks / use Spring's core testing annotations
  ** Build-time AOT processing
    *** EACH unique test `ApplicationContext` | current project -- will be -- xref:core/aot.adoc#aot.refresh[refreshed for AOT processing]
  ** Runtime AOT support
    *** executing | AOT runtime mode, Spring integration test -- will
  use an -- AOT-optimized `ApplicationContext` / participates transparently with the xref:testing/testcontext-framework/ctx-management/caching.adoc[context cache]

* ALL tests, by default, are enabled in AOT mode
  ** if you want to selectively disable an entire test class or individual test method in AOT mode -> annotate it with xref:testing/annotations/integration-spring/annotation-disabledinaotmode.adoc[`@DisabledInAotMode`]
    *** ALSO valid, running | GraalVM native image
  ** if you use JUnit Jupiter -> you may selectively enable or disable tests | GraalVM native image -- via --
    *** Jupiter's `@EnabledInNativeImage`
    *** `@DisabledInNativeImage`

* if an error is encountered | build-time AOT processing -> by default, an exception -- will be -- thrown == overall process will fail IMMEDIATELY
  ** if you want that build-time AOT processing continue AFTER errors -> disable the `failOnError` mode
    *** 👀`failOnError` mode 👀
      **** logs at
        ***** `WARN` level or
        ***** `DEBUG` level / greater detail
      **** ways to disable
        ***** | CL
        ***** build script -- by setting -- `spring.test.aot.processing.failOnError=false`
        ***** set -- via -- xref:appendix.adoc#appendix-spring-properties[`SpringProperties`] mechanism

* `@ContextHierarchy` annotation
  ** NOT supported | AOT mode

* test-specific runtime hints for use | GraalVM native image
    ** implement a custom
  {spring-framework-api}/test/context/aot/TestRuntimeHintsRegistrar.html[`TestRuntimeHintsRegistrar`]
        *** register it globally -- via -- `META-INF/spring/aot.factories`
        *** companion to the core `RuntimeHintsRegistrar` API
    ** implement a custom {spring-framework-api}/aot/hint/RuntimeHintsRegistrar.html[`RuntimeHintsRegistrar`]
        *** register it
            **** globally -- via -- `META-INF/spring/aot.factories` or
            **** locally | test class -- via -- {spring-framework-api}/context/annotation/ImportRuntimeHints.html[`@ImportRuntimeHints`]
        *** use cases
            **** register global hints for testing support / NOT specific to particular test classes
    ** annotate a test class with
        *** {spring-framework-api}/aot/hint/annotation/Reflective.html[`@Reflective`] or
        *** {spring-framework-api}/aot/hint/annotation/RegisterReflectionForBinding.html[`@RegisterReflectionForBinding`]
    ** see xref:core/aot.adoc#aot.hints[Runtime Hints]


* if you implement a custom `ContextLoader` -> implement
{spring-framework-api}/test/context/aot/AotContextLoader.html[`AotContextLoader`]
    ** Reason: 🧠 provide AOT build-time processing & AOT runtime execution support 🧠
    ** ALL context loader implementations / provided by the Spring Framework &
Spring Boot -> ALREADY implement `AotContextLoader`

* If you implement a custom `TestExecutionListener` -> implement
{spring-framework-api}/test/context/aot/AotTestExecutionListener.html[`AotTestExecutionListener`]
    ** Reason: 🧠participate in AOT processing 🧠
    ** see the `SqlScriptsTestExecutionListener` | `spring-test` module
