[[testcontext-application-events]]
= Application Events

* TestContext framework
    ** -- provides support for -- recording
xref:core/beans/context-introduction.adoc#context-functionality-events[application events] / published |
`ApplicationContext`
        *** -> assertions -- can be performed against -- those events | tests
        *** ALL events published | 1! test execution -- are made available via
the -- `ApplicationEvents` API
            **** -> can be processed -- as a -- `java.util.Stream`

* steps to use `ApplicationEvents` | your tests
    ** your test class -- MUST be annotated or meta-annotated with --
  xref:testing/annotations/integration-spring/annotation-recordapplicationevents.adoc[`@RecordApplicationEvents`]
    ** `ApplicationEventsTestExecutionListener` is registered
        *** by default, `ApplicationEventsTestExecutionListener` is registered
        *** if you have custom configuration via
  `@TestExecutionListeners` / NOT include the default listeners -> needs
to be MANUALLY registered
    ** annotate a field of type `ApplicationEvents` with `@Autowired` & use that instance of
  `ApplicationEvents` | your test & lifecycle methods (`@BeforeEach` and
  `@AfterEach` methods | JUnit Jupiter)
        *** if you use the xref:testing/testcontext-framework/support-classes.adoc#testcontext-junit-jupiter-extension[SpringExtension for JUnit Jupiter] -> you MAY declare, as an alternative to an `@Autowired` field | test class, a method
   parameter of type `ApplicationEvents` |
            **** test or
            **** lifecycle method

* _Example:_ test class / uses the `SpringExtension` for JUnit Jupiter &
{assertj-docs}[AssertJ]
    ** Reason: 🧠 assert the types of application events published | invoking a method in a Spring-managed component 🧠

// Don't use "quotes" in the "subs" section because of the asterisks in /* ... */
[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim",role="primary"]
----
	@SpringJUnitConfig(/* ... */)
	@RecordApplicationEvents
	class OrderServiceTests {

		@Autowired
		OrderService orderService;

		@Autowired
		ApplicationEvents events; // Inject the `ApplicationEvents` instance for the current test

		@Test
		void submitOrder() {
			// Invoke method in OrderService that publishes an event
			orderService.submitOrder(new Order(/* ... */));
			// Verify that an OrderSubmitted event was published
			long numEvents = events.stream(OrderSubmitted.class).count(); // count `OrderSubmitted` events -- via -- `ApplicationEvents` API
			assertThat(numEvents).isEqualTo(1);
		}
	}
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim",role="secondary"]
----
	@SpringJUnitConfig(/* ... */)
	@RecordApplicationEvents
	class OrderServiceTests {

		@Autowired
		lateinit var orderService: OrderService

		@Autowired
		lateinit var events: ApplicationEvents // Inject the `ApplicationEvents` instance for the current test

		@Test
		fun submitOrder() {
			// Invoke method in OrderService that publishes an event
			orderService.submitOrder(Order(/* ... */))
			// Verify that an OrderSubmitted event was published
			val numEvents = events.stream(OrderSubmitted::class).count() // count `OrderSubmitted` events -- via -- `ApplicationEvents` API
			assertThat(numEvents).isEqualTo(1)
		}
	}
----
======

* see
{spring-framework-api}/test/context/event/ApplicationEvents.html[`ApplicationEvents`
javadoc]
