[[testcontext-bootstrapping]]
= Bootstrapping the TestContext Framework

* default configuration for the internals of the Spring TestContext Framework
    ** 👀sufficient for ALL common use cases 👀

* Spring's bootstrapping strategy
    ** == low-level control over how the TestContext framework operates / allows making changes about
        *** default `ContextLoader`
        *** implement a custom `TestContext` or `ContextCache`
        *** augment the default sets of `ContextCustomizerFactory` & `TestExecutionListener` implementations

* `@BootstrapWith`
    ** allows configuring a custom bootstrapping strategy | test class (or test class hierarchy) -- by using it --
        *** directly or
        *** as a meta-annotation
    ** if a bootstrapper is NOT explicitly configured | `@BootstrapWith` &
        *** `@WebAppConfiguration` is -> `WebTestContextBootstrapper` is used
        *** `@WebAppConfiguration` is NOT -> `DefaultTestContextBootstrapper`

* `TestContextBootstrapper`
    ** defines the SPI -- for -- bootstrapping the TestContext framework
    ** uses
        *** by the `TestContextManager` -- to --
            **** load the `TestExecutionListener` implementations | current test
            **** build the `TestContext` / it manages
    ** recommendations
        *** NOT to implement this interface directly, but rather to extend `AbstractTestContextBootstrapper` or one of its concrete
subclasses
            **** Reason: 🧠`TestContextBootstrapper` SPI is likely to change in the future 🧠
