[[testcontext-fixture-di]]
= Dependency Injection of Test Fixtures

* `DependencyInjectionTestExecutionListener`
    ** configured by default
    ** ways to inject, from beans -- test instances' dependencies | application context / you configure
        *** setter injection,
            **** allowed
                ***** Spring's `@Autowired`
                ***** `@Inject` from JSR-330
        *** field injection,
            **** allowed
                ***** Spring's `@Autowired`
                ***** `@Inject` from JSR-330
            **** uses
                ***** | production code , discouraged
                ***** | test code, quite natural
        *** both
        *** constructor injection
            **** requirements: you use JUnit Jupiter
            **** see xref:testing/testcontext-framework/support-classes.adoc#testcontext-junit-jupiter-di[Dependency Injection + `SpringExtension`])

* TestContext framework about testing frameworks / != JUnit Jupiter
    ** 👀does NOT participate in instantiation of the test class 👀
        *** -> if you use `@Autowired` or `@Inject` for constructors -> NOT effect for test classes

* instantiate your test class
    ** NEVER done directly
        *** -> NO need to invoke | your test class, a
            **** `public` constructor or
            **** setter method

* `@Autowired`
    ** uses
        *** perform xref:core/beans/dependencies/factory-autowire.adoc[autowiring by type]
            **** if you have MULTIPLE bean definitions / SAME type
                ***** -> you can NOT rely on it
                ***** + `@Qualifier("specificTargetBean")` -- is matched against --
                ****** `<qualifier>` declarations | corresponding `<bean>` definitions or
                ****** bean name (as fall back)
                ****** _Example:_ you are extending from a Spring-provided test base class
+
[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	// ...

		@Autowired
		@Override
		public void setDataSource(@Qualifier("myDataSource") DataSource dataSource) {
			super.setDataSource(dataSource);
		}

	// ...
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	// ...

		@Autowired
		override fun setDataSource(@Qualifier("myDataSource") dataSource: DataSource) {
			super.setDataSource(dataSource)
		}

	// ...
----
======
                ***** use as alternative: `@Inject` + `@Named`

* if your test class has access to its `ApplicationContext` -> perform an explicit lookup
    ** _Example:_ call to `applicationContext.getBean("titleRepository", TitleRepository.class)`

* if you do NOT want DI applied | your test instances
    ** NOT annotate fields or setter methods with `@Autowired` or `@Inject`
    ** disable DI ALTOGETHER -- by explicitly configuring -- your class with `@TestExecutionListeners` & omit `DependencyInjectionTestExecutionListener.class` from the list of listeners

* _Example:_ test a `HibernateTitleRepository` class, as xref:testing/integration.adoc#integration-testing-goals[Goals] section
    ** use `@Autowired` | fields & setter methods
    ** application context configuration
    ** DI behavior NOT specific to JUnit Jupiter
        *** == same DI techniques -- can be used with -- ANY supported testing framework
    ** _Example1:_ JUnit Jupiter based implementation of the test class / uses `@Autowired` | field injection
+
[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	@ExtendWith(SpringExtension.class)
	// specifies the Spring configuration to load for this test fixture
	@ContextConfiguration("repository-config.xml")
	class HibernateTitleRepositoryTests {

		// this instance will be dependency injected by type
		@Autowired
		HibernateTitleRepository titleRepository;

		@Test
		void findById() {
			Title title = titleRepository.findById(new Long(10));
			assertNotNull(title);
		}
	}
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	@ExtendWith(SpringExtension::class)
	// specifies the Spring configuration to load for this test fixture
	@ContextConfiguration("repository-config.xml")
	class HibernateTitleRepositoryTests {

		// this instance will be dependency injected by type
		@Autowired
		lateinit var titleRepository: HibernateTitleRepository

		@Test
		fun findById() {
			val title = titleRepository.findById(10)
			assertNotNull(title)
		}
	}
----
======

    ** _Example2:_ alternative to Example1, configuring the class to use `@Autowired` | setter injection
+
[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	@ExtendWith(SpringExtension.class)
	// specifies the Spring configuration to load for this test fixture
	@ContextConfiguration("repository-config.xml")
	class HibernateTitleRepositoryTests {

		// this instance will be dependency injected by type
		HibernateTitleRepository titleRepository;

        // setter injection
		@Autowired
		void setTitleRepository(HibernateTitleRepository titleRepository) {
			this.titleRepository = titleRepository;
		}

		@Test
		void findById() {
			Title title = titleRepository.findById(new Long(10));
			assertNotNull(title);
		}
	}
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	@ExtendWith(SpringExtension::class)
	// specifies the Spring configuration to load for this test fixture
	@ContextConfiguration("repository-config.xml")
	class HibernateTitleRepositoryTests {

		// this instance will be dependency injected by type
		lateinit var titleRepository: HibernateTitleRepository

        // setter injection
		@Autowired
		fun setTitleRepository(titleRepository: HibernateTitleRepository) {
			this.titleRepository = titleRepository
		}

		@Test
		fun findById() {
			val title = titleRepository.findById(10)
			assertNotNull(title)
		}
	}
----
======

    ** _Example:_ `repository-config.xml`
+
[source,xml,indent=0,subs="verbatim,quotes"]
----
	<?xml version="1.0" encoding="UTF-8"?>
	<beans xmlns="http://www.springframework.org/schema/beans"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://www.springframework.org/schema/beans
			https://www.springframework.org/schema/beans/spring-beans.xsd">

		<!-- this bean will be injected into the HibernateTitleRepositoryTests class -->
		<bean id="titleRepository" class="com.foo.repository.hibernate.HibernateTitleRepository">
			<property name="sessionFactory" ref="sessionFactory"/>
		</bean>

		<bean id="sessionFactory" class="org.springframework.orm.hibernate5.LocalSessionFactoryBean">
			<!-- configuration elided for brevity -->
		</bean>

	</beans>
----
