[[testcontext-key-abstractions]]
= Key Abstractions

* Spring TestContext Framework == `TestContextManager` + `TestContext` + `TestExecutionListener` + `SmartContextLoader`
  ** `TestContextManager`
    *** created / test class
      **** _Example:_ / execution of ALL test methods | 1! test class in JUnit Jupiter
    *** manages a `TestContext`
      **** as the test progresses -> update the `TestContext`
    *** delegates to `TestExecutionListener` implementations
  ** `TestContext`
    *** holds the context of the current test
  ** `TestExecutionListener`
    *** instrument the actual test execution -- by --
      **** providing dependency injection,
      **** managing transactions
      **** ...
  ** `SmartContextLoader`
    *** loads an `ApplicationContext` / given test class
    *** Check {spring-framework-api}/test/context/package-summary.html[javadoc] + Spring test suite

[[testcontext]]
== `TestContext`

* allows
  ** context | test is run -> is encapsulated  / agnostic to the used testing framework
  ** context management and caching support | test instance / is responsible
* if loading an `ApplicationContext` is necessary -> delegates to a `SmartContextLoader`

[[testcontextmanager]]
== `TestContextManager`

* TODO:
`TestContextManager` is the main entry point into the Spring TestContext Framework and is
responsible for managing a single `TestContext` and signaling events to each registered
`TestExecutionListener` at well-defined test execution points:

* Prior to any "`before class`" or "`before all`" methods of a particular testing framework.
* Test instance post-processing.
* Prior to any "`before`" or "`before each`" methods of a particular testing framework.
* Immediately before execution of the test method but after test setup.
* Immediately after execution of the test method but before test tear down.
* After any "`after`" or "`after each`" methods of a particular testing framework.
* After any "`after class`" or "`after all`" methods of a particular testing framework.

[[testexecutionlistener]]
== `TestExecutionListener`

`TestExecutionListener` defines the API for reacting to test-execution events published by
the `TestContextManager` with which the listener is registered. See xref:testing/testcontext-framework/tel-config.adoc[`TestExecutionListener` Configuration].

[[context-loaders]]
== Context Loaders

* := strategy interface -- for -- loading an `ApplicationContext` | integration test / managed by the Spring TestContext Framework
* `ContextLoader`
  ** := interface / 👁️recommended NOT implement it 👁️
* `SmartContextLoader`
  ** := interface /
    *** 👁️recommended to implement it 👁️
    *** extends from `ContextLoader`
  ** provide support for
    *** component classes,
    *** active bean definition profiles,
    *** test property sources,
    *** context hierarchies,
    *** `WebApplicationContext`
* built-in implementations
  ** `DelegatingSmartContextLoader`
    *** One of two default loaders, it delegates internally to
  an `AnnotationConfigContextLoader`, a `GenericXmlContextLoader`, or a
  `GenericGroovyXmlContextLoader`, depending either on the configuration declared for the
  test class or on the presence of default locations or default configuration classes.
  Groovy support is enabled only if Groovy is on the classpath.
  ** `WebDelegatingSmartContextLoader`
    *** One of two default loaders, it delegates internally
  to an `AnnotationConfigWebContextLoader`, a `GenericXmlWebContextLoader`, or a
  `GenericGroovyXmlWebContextLoader`, depending either on the configuration declared for
  the test class or on the presence of default locations or default configuration
  classes. A web `ContextLoader` is used only if `@WebAppConfiguration` is present on the
  test class. Groovy support is enabled only if Groovy is on the classpath.
  ** `AnnotationConfigContextLoader`
    *** Loads a standard `ApplicationContext` from component
  classes.
  ** `AnnotationConfigWebContextLoader`
    *** Loads a `WebApplicationContext` from component
  classes.
  ** `GenericGroovyXmlContextLoader`
    *** Loads a standard `ApplicationContext` from resource
  locations that are either Groovy scripts or XML configuration files.
  ** `GenericGroovyXmlWebContextLoader`
    *** Loads a `WebApplicationContext` from resource
  locations that are either Groovy scripts or XML configuration files.
  ** `GenericXmlContextLoader`
    *** Loads a standard `ApplicationContext` from XML resource
  locations.
  ** `GenericXmlWebContextLoader`
    *** Loads a `WebApplicationContext` from XML resource
  locations.


