[[message-converters]]
= HTTP Message Conversion

* [.small]#xref:web/webflux/reactive-spring.adoc#webflux-codecs[== in the Reactive stack]#

* `HttpMessageConverter`
    ** uses
        *** | `spring-web`, for
            **** reading -- through `InputStream` -- the body of HTTP requests
            **** writing -- through `OutputStream` -- the body of HTTP responses
        *** | client side
            **** _Example:_ `RestClient`
        *** | server side
            **** _Example:_ Spring MVC REST controllers
* Implementations for the main media (MIME) types
    ** xref:web/webmvc/mvc-config/message-converters.adoc[Configuring Message Converters]
    ** are provided in the framework, by default, registered
        *** | client side, with the
            **** `RestClient`
            **** `RestTemplate`
        *** | server side, with the
            **** `RequestMappingHandlerAdapter`
    ** 👁️default media type / converter 👁️
        *** `.supportedMediaTypes` overrides the media type

[[rest-message-converters-tbl]]
.HttpMessageConverter Implementations
[cols="1,3"]
|===
| MessageConverter | Description

| `StringHttpMessageConverter`
| - `HttpMessageConverter` implementation / can +
&nbsp; &nbsp; - read `String` instances -- from the -- HTTP request +
&nbsp; &nbsp; - write `String` instances -- to the -- HTTP response / `Content-Type:text/plain` +
- ALL text media types(`text/{asterisk}`) are supported

| `FormHttpMessageConverter`
| An `HttpMessageConverter` implementation that can read and write form data from the HTTP request and response.
By default, this converter reads and writes the `application/x-www-form-urlencoded` media type.
Form data is read from and written into a `MultiValueMap<String, String>`.
The converter can also write (but not read) multipart data read from a `MultiValueMap<String, Object>`.
By default, `multipart/form-data` is supported.
Additional multipart subtypes can be supported for writing form data.
Consult the javadoc for `FormHttpMessageConverter` for further details.

| `ByteArrayHttpMessageConverter`
| - `HttpMessageConverter` implementation / can +
&nbsp; &nbsp; - read `[]byte` -- from the -- HTTP request +
&nbsp; &nbsp; - write `[]byte` -- to the -- HTTP response / `Content-Type:application/octet-stream` +
- ALL text media types(`text/{asterisk}`) are supported +
- if you want to override the media types -> override `getContentType(byte[])`

| `MarshallingHttpMessageConverter`
| An `HttpMessageConverter` implementation that can read and write XML by using Spring's `Marshaller` and `Unmarshaller` abstractions from the `org.springframework.oxm` package.
This converter requires a `Marshaller` and `Unmarshaller` before it can be used.
You can inject these through constructor or bean properties.
By default, this converter supports `text/xml` and `application/xml`.

| `MappingJackson2HttpMessageConverter`
| An `HttpMessageConverter` implementation that can read and write JSON by using Jackson's `ObjectMapper`.
You can customize JSON mapping as needed through the use of Jackson's provided annotations.
When you need further control (for cases where custom JSON serializers/deserializers need to be provided for specific types), you can inject a custom `ObjectMapper` through the `ObjectMapper` property.
By default, this converter supports `application/json`. This requires the `com.fasterxml.jackson.core:jackson-databind` dependency.

| `MappingJackson2XmlHttpMessageConverter`
| An `HttpMessageConverter` implementation that can read and write XML by using {jackson-github-org}/jackson-dataformat-xml[Jackson XML] extension's `XmlMapper`.
You can customize XML mapping as needed through the use of JAXB or Jackson's provided annotations.
When you need further control (for cases where custom XML serializers/deserializers need to be provided for specific types), you can inject a custom `XmlMapper` through the `ObjectMapper` property.
By default, this converter supports `application/xml`. This requires the `com.fasterxml.jackson.dataformat:jackson-dataformat-xml` dependency.

| `MappingJackson2CborHttpMessageConverter`
| `com.fasterxml.jackson.dataformat:jackson-dataformat-cbor`

| `SourceHttpMessageConverter`
| An `HttpMessageConverter` implementation that can read and write `javax.xml.transform.Source` from the HTTP request and response.
Only `DOMSource`, `SAXSource`, and `StreamSource` are supported.
By default, this converter supports `text/xml` and `application/xml`.

| `GsonHttpMessageConverter`
| An `HttpMessageConverter` implementation that can read and write JSON by using "Google Gson".
This requires the `com.google.code.gson:gson` dependency.

| `JsonbHttpMessageConverter`
| An `HttpMessageConverter` implementation that can read and write JSON by using the Jakarta Json Bind API.
This requires the `jakarta.json.bind:jakarta.json.bind-api` dependency and an implementation available.

| `ProtobufHttpMessageConverter`
| An `HttpMessageConverter` implementation that can read and write Protobuf messages in binary format with the `"application/x-protobuf"`
content type. This requires the `com.google.protobuf:protobuf-java` dependency.

| `ProtobufJsonFormatHttpMessageConverter`
| An `HttpMessageConverter` implementation that can read and write JSON documents to and from Protobuf messages.
This requires the `com.google.protobuf:protobuf-java-util` dependency.

|===


