[[mvc-config-enable]]
= Enable MVC Configuration

* [.small]#xref:web/webflux/config.adoc#webflux-config-enable[== in the Reactive stack]#
* ways to enable MVC configuration
    ** `@EnableWebMvc` == programmatic configuration
        *** _Example:_

            include-code::./WebConfiguration[tag=snippet,indent=0]

            **** Spring MVC xref:web/webmvc/mvc-servlet/special-bean-types.adoc[infrastructure beans] are registered
            **** dependencies / available on the classpath ( -- _Example:_ payload converters for JSON, XML, ...) are adapted
    ** `<mvc:annotation-driven>` == XML configuration


* if you are using Spring Boot & ⚠️️ want to keep ⚠️ Spring Boot MVC customizations -> | classes of type `WebMvcConfigurer`,
    ** use
        *** `@Configuration`
        *** 👁️ BUT NOT `@EnableWebMvc`  👁️
    ** Check
        *** xref:web/webmvc/mvc-config/customize.adoc[MVC Config API section]
        *** {spring-boot-docs}/web.html#web.servlet.spring-mvc.auto-configuration[dedicated Spring Boot documentation]
