[[mvc-config-message-converters]]
= Message Converters

* [.small]#xref:web/webflux/config.adoc#webflux-config-message-codecs[== in the Reactive stack]#

* `HttpMessageConverter` instances
    ** ðŸ‘ï¸ there are default ones ðŸ‘ï¸
    ** can be
        *** overrided -- via -- overriding {spring-framework-api}/web/servlet/config/annotation/WebMvcConfigurer.html#configureMessageConverters[`.configureMessageConverters()`]
            *** customized-- via -- overriding {spring-framework-api}/web/servlet/config/annotation/WebMvcConfigurer.html#extendMessageConverters[`.extendMessageConverters()`]
    ** | Spring Boot application, recommended to use
        *** {spring-boot-docs}/web.html#web.servlet.spring-mvc.message-converters[HttpMessageConverters] mechanism
        *** `.extendMessageConverters()`

* _Example:_
    ** adds XML and Jackson JSON converters / customized `ObjectMapper` -- rather than default ones --
    ** if next modules are detected | classpath -> registered automatically
        *** {jackson-github-org}/jackson-datatype-joda[jackson-datatype-joda]
            **** -- support for -- Joda-Time types
        *** {jackson-github-org}/jackson-datatype-jsr310[jackson-datatype-jsr310]
            **** -- support for -- Java 8 Date and Time API types
        *** {jackson-github-org}/jackson-datatype-jdk8[jackson-datatype-jdk8]
            **** -- support for -- other Java 8 types -- _Example:_ `Optional` --
        *** {jackson-github-org}/jackson-module-kotlin[jackson-module-kotlin]
            **** -- support for -- Kotlin classes and data classes

include-code::./WebConfiguration[tag=snippet,indent=0]

* if you want to enable indentation with Jackson XML -> required
    ** https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.codehaus.woodstox%22%20AND%20a%3A%22woodstox-core-asl%22[`woodstox-core-asl`]
    ** https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22jackson-dataformat-xml%22[`jackson-dataformat-xml`]
* other interesting Jackson modules
    ** https://github.com/zalando/jackson-datatype-money[jackson-datatype-money]
        *** -- support for -- `javax.money` types (unofficial module)
    ** {jackson-github-org}/jackson-datatype-hibernate[jackson-datatype-hibernate]
        *** -- support for -- Hibernate-specific types and properties (ALSO lazy-loading aspects)
