[[mvc-config-static-resources]]
= Static Resources

* [.small]#xref:web/webflux/config.adoc#webflux-config-static-resources[== in the Reactive stack]#

* allows
    ** from a list of {spring-framework-api}/core/io/Resource.html[`Resource`]-based locations -- serve -- static resources
        *** Check xref:web/webmvc/mvc-caching.adoc#mvc-caching-static-resources[HTTP caching support for static resources]
        *** _Example:_

        include-code::./WebConfiguration[tag=snippet,indent=0]

* Resource handler to work with
    ** optimized resources
        *** {spring-framework-api}/web/servlet/resource/ResourceResolver.html[`ResourceResolver`] implementations + {spring-framework-api}/web/servlet/resource/ResourceTransformer.html[`ResourceTransformer`] implementations
    ** versioned resource URLs -- based on -- MD5 hash / computed from the content, a fixed application version, ..
        *** Note: ðŸ‘ï¸ `ContentVersionStrategy` (MD5 hash) is a good choice, except to JS resources / module loader ðŸ‘ï¸
        *** `VersionResourceResolver`

            include-code::./VersionedConfiguration[tag=snippet,indent=0]

* `ResourceUrlProvider`
    ** allows
        *** rewriting URLs
        *** applying the full chain of resolvers and transformers -- _Example:_ insert versions --
    ** MVC configuration -- provides a -- `ResourceUrlProvider` bean
        *** -> can be injected into others
* `ResourceUrlEncodingFilter`
    ** allows
        *** rewriting URL transparently / for Thymeleaf, JSPs, FreeMarker -- via -- URL tags / rely on `HttpServletResponse#encodeURL`
* `EncodedResourceResolver`
    ** uses
        *** serving gzipped OR brotli-encoded resources
    ** + `VersionResourceResolver` ->  must register them in this (which one?) order
        *** Reason: ðŸ§  content-based versions are always computed reliably == based on the unencoded file ðŸ§ 
* For https://www.webjars.org/documentation[WebJars]
    ** if versioned URLs (-- _Example:_ `/webjars/jquery/1.2.0/jquery.min.js` --)
        *** the most recommended and efficient way to use them
        *** related resource location
            **** configured
                ***** out of the box with Spring Boot OR
                ***** manually -- via -- `ResourceHandlerRegistry` (Java configuration)
                    ****** -> fine-grained control & further options
            **** NOT required to add the `org.webjars:webjars-locator-core` dependency
    ** if version-less URLs (-- _Example:_ `/webjars/jquery/jquery.min.js` --)
        *** -- supported through -- the `WebJarsResourceResolver`
            **** if `org.webjars:webjars-locator-core` library is present on the classpath -> register it
            **** allows
                ***** URLs -- are re-written, to include -- version of the jar
                    ****** _Example:_ `/webjars/jquery/jquery.min.js` to `/webjars/jquery/1.2.0/jquery.min.js`
                ***** matching against incoming URLs without versions (?)
