[[expressions-evaluation]]
= Evaluation

* goal
	** SpEL's expression language
		*** check also xref:core/expressions/language-ref.adoc[Language Reference]
	** SpEL's interfaces, how to use it programmatically
		*** _Example:_ evaluate the literal string expression, `Hello World`

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	ExpressionParser parser = new SpelExpressionParser();
	Expression exp = parser.parseExpression("'Hello World'"); 
	String message = (String) exp.getValue();
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	val parser = SpelExpressionParser()
	val exp = parser.parseExpression("'Hello World'") 
	val message = exp.value as String
----
======

* `org.springframework.expression` + it's subpackages
	** == most of the SpEL classes and interfaces -- _Example:_ `spel.support` --
* `ExpressionParser`
	** := interface / -- responsible for -- parsing an expression string
		*** expression string := string literal / surrounded by single quotation marks ('')
	** `.parseExpression(...)` -- can throw -- `ParseException`
* `Expression`
	** := interface / -- responsible for -- evaluating the defined expression string
	** `.getValue(...)` -- can throw -- `EvaluationException`
* SpEL features
	** calling methods,
		*** _Example:_ `.concat()`
	** accessing properties,
		*** _Example1:_ `.getValue()` to access the string literal's `Bytes` JavaBean property
		*** also nested properties
			**** _Example:_ `.bytes.length`
		*** _Example2:_ `public <T> T getValue(Class<T> desiredResultType)` -> -- NOT need to cast to the -- desired result type
	** calling constructors
		*** alternative to use a string literal

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	ExpressionParser parser = new SpelExpressionParser();
	Expression exp = parser.parseExpression("'Hello World'.concat('!')"); 
	String message = (String) exp.getValue();
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	val parser = SpelExpressionParser()
	val exp = parser.parseExpression("'Hello World'.concat('!')") 
	val message = exp.value as String
----
======


[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	ExpressionParser parser = new SpelExpressionParser();

	// invokes 'getBytes()'
	Expression exp = parser.parseExpression("'Hello World'.bytes"); // string literal -- to -> byte array
	byte[] bytes = (byte[]) exp.getValue();
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	val parser = SpelExpressionParser()

	// invokes 'getBytes()'
	val exp = parser.parseExpression("'Hello World'.bytes") // string literal -- to -> byte array
	val bytes = exp.value as ByteArray
----
======



[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	ExpressionParser parser = new SpelExpressionParser();

	// invokes 'getBytes().length'
	Expression exp = parser.parseExpression("'Hello World'.bytes.length"); 
	int length = (Integer) exp.getValue();
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	val parser = SpelExpressionParser()

	// invokes 'getBytes().length'
	val exp = parser.parseExpression("'Hello World'.bytes.length") 
	val length = exp.value as Int
----
======


[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	ExpressionParser parser = new SpelExpressionParser();
	Expression exp = parser.parseExpression("new String('hello world').toUpperCase()"); // new String('') == via constructor
	String message = exp.getValue(String.class);  // getValue(Class<T> desiredResultType)  ==  NO need to cast
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	val parser = SpelExpressionParser()
	val exp = parser.parseExpression("new String('hello world').toUpperCase()")  // new String('') == via constructor
	val message = exp.getValue(String::class.java)	// getValue(Class<T> desiredResultType)  ==  NO need to cast
----
======

* SpEL use cases
	** provide an expression string / -- is evaluated against a -- specific object instance (:= root object)
		*** _Example:_ from an instance of the `Inventor` class -> retrieve the `name` property + reference the `name` property | boolean expression

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	// Create and set a calendar
	GregorianCalendar c = new GregorianCalendar();
	c.set(1856, 7, 9);

	// constructor arguments are name, birthday, and nationality.
	Inventor tesla = new Inventor("Nikola Tesla", c.getTime(), "Serbian");

	ExpressionParser parser = new SpelExpressionParser();

	Expression exp = parser.parseExpression("name"); // Parse name as an expression
	String name = (String) exp.getValue(tesla);	// specific object instance
	// name == "Nikola Tesla"

	exp = parser.parseExpression("name == 'Nikola Tesla'");
	boolean result = exp.getValue(tesla, Boolean.class); // if the value can NOT be casted to Boolean -> `EvaluationException` is thrown
	// result == true
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	// Create and set a calendar
	val c = GregorianCalendar()
	c.set(1856, 7, 9)

	// The constructor arguments are name, birthday, and nationality.
	val tesla = Inventor("Nikola Tesla", c.time, "Serbian")

	val parser = SpelExpressionParser()

	var exp = parser.parseExpression("name") // Parse name as an expression
	val name = exp.getValue(tesla) as String
	// name == "Nikola Tesla"

	exp = parser.parseExpression("name == 'Nikola Tesla'")
	val result = exp.getValue(tesla, Boolean::class.java)	// if the value can NOT be casted to Boolean -> `EvaluationException` is thrown
	// result == true
----
======



[[expressions-evaluation-context]]
== Understanding `EvaluationContext`

* := interface / 
	** evaluate an expression -- to 
		*** resolve -- properties, methods, or fields
		*** help perform -- type conversion
* implementations / provided by Spring
	** `SimpleEvaluationContext`
		*** == subset of essential SpEL language features + configuration options | categories of expressions / NOT require the full extent of the SpEL language syntax
			**** excluded
				***** Java type references
				***** constructors
				***** bean references
			**** requires
				***** choose the level of support for properties and methods | expressions
					****** _Example:_ `create()` == static factory method / -- by default, ONLY -- read access to properties
					****** ways
						******* explicitly 
						******* builder / target is 1 or several of
							******** Custom `PropertyAccessor` only (no reflection)
							******** Data binding properties -- for -- read-only access
							******** Data binding properties -- for -- read and write
		*** _Examples:_ data binding expressions and property-based filters
	** `StandardEvaluationContext`
		*** == full set of SpEL language features + configuration options
		*** uses
			**** specify a default root object
			**** configure every available evaluation-related strategy


[[expressions-type-conversion]]
=== SpEL Type Conversion

* -- via, by default, -- `org.springframework.core.convert.ConversionService`
	** == conversion service | Spring core
	** many built-in converters
	** fully extensible -> you can add custom conversions between types
	** generics-aware
		*** == if you work with generic types | expressions -> SpEL attempts conversions / maintain type correctness
		*** _Example:_ pass `setValue(StringList)` / BooleanList is required -> convert it in advance

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	class Simple {
		public List<Boolean> booleanList = new ArrayList<>();
	}

	Simple simple = new Simple();
	simple.booleanList.add(true);

	EvaluationContext context = SimpleEvaluationContext.forReadOnlyDataBinding().build();

	// "false" == String
	// SpEL and the conversion service -- recognizes that -- Boolean is needed -> convert it accordingly
	parser.parseExpression("booleanList[0]").setValue(context, simple, "false");

	// b is false
	Boolean b = simple.booleanList.get(0);
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	class Simple {
		var booleanList: MutableList<Boolean> = ArrayList()
	}

	val simple = Simple()
	simple.booleanList.add(true)

	val context = SimpleEvaluationContext.forReadOnlyDataBinding().build()

	// "false" == String
	// SpEL and the conversion service -- recognizes that -- Boolean is needed -> convert it accordingly
	parser.parseExpression("booleanList[0]").setValue(context, simple, "false")

	// b is false
	val b = simple.booleanList[0]
----
======


[[expressions-parser-configuration]]
== Parser Configuration

// TODO:
It is possible to configure the SpEL expression parser by using a parser configuration
object (`org.springframework.expression.spel.SpelParserConfiguration`). The configuration
object controls the behavior of some of the expression components. For example, if you
index into an array or collection and the element at the specified index is `null`, SpEL
can automatically create the element. This is useful when using expressions made up of a
chain of property references. If you index into an array or list and specify an index
that is beyond the end of the current size of the array or list, SpEL can automatically
grow the array or list to accommodate that index. In order to add an element at the
specified index, SpEL will try to create the element using the element type's default
constructor before setting the specified value. If the element type does not have a
default constructor, `null` will be added to the array or list. If there is no built-in
or custom converter that knows how to set the value, `null` will remain in the array or
list at the specified index. The following example demonstrates how to automatically grow
the list.

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	class Demo {
		public List<String> list;
	}

	// Turn on:
	// - auto null reference initialization
	// - auto collection growing
	SpelParserConfiguration config = new SpelParserConfiguration(true, true);

	ExpressionParser parser = new SpelExpressionParser(config);

	Expression expression = parser.parseExpression("list[3]");

	Demo demo = new Demo();

	Object o = expression.getValue(demo);

	// demo.list will now be a real collection of 4 entries
	// Each entry is a new empty String
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	class Demo {
		var list: List<String>? = null
	}

	// Turn on:
	// - auto null reference initialization
	// - auto collection growing
	val config = SpelParserConfiguration(true, true)

	val parser = SpelExpressionParser(config)

	val expression = parser.parseExpression("list[3]")

	val demo = Demo()

	val o = expression.getValue(demo)

	// demo.list will now be a real collection of 4 entries
	// Each entry is a new empty String
----
======

By default, a SpEL expression cannot contain more than 10,000 characters; however, the
`maxExpressionLength` is configurable. If you create a `SpelExpressionParser`
programmatically, you can specify a custom `maxExpressionLength` when creating the
`SpelParserConfiguration` that you provide to the `SpelExpressionParser`. If you wish to
set the `maxExpressionLength` used for parsing SpEL expressions within an
`ApplicationContext` -- for example, in XML bean definitions, `@Value`, etc. -- you can
set a JVM system property or Spring property named `spring.context.expression.maxLength`
to the maximum expression length needed by your application (see
xref:appendix.adoc#appendix-spring-properties[Supported Spring Properties]).


[[expressions-spel-compilation]]
== SpEL Compilation

Spring provides a basic compiler for SpEL expressions. Expressions are usually
interpreted, which provides a lot of dynamic flexibility during evaluation but does not
provide optimum performance. For occasional expression usage, this is fine, but, when
used by other components such as Spring Integration, performance can be very important,
and there is no real need for the dynamism.

The SpEL compiler is intended to address this need. During evaluation, the compiler
generates a Java class that embodies the expression behavior at runtime and uses that
class to achieve much faster expression evaluation. Due to the lack of typing around
expressions, the compiler uses information gathered during the interpreted evaluations
of an expression when performing compilation. For example, it does not know the type
of a property reference purely from the expression, but during the first interpreted
evaluation, it finds out what it is. Of course, basing compilation on such derived
information can cause trouble later if the types of the various expression elements
change over time. For this reason, compilation is best suited to expressions whose
type information is not going to change on repeated evaluations.

Consider the following basic expression.

[source,java,indent=0,subs="verbatim,quotes"]
----
	someArray[0].someProperty.someOtherProperty < 0.1
----

Because the preceding expression involves array access, some property de-referencing, and
numeric operations, the performance gain can be very noticeable. In an example micro
benchmark run of 50,000 iterations, it took 75ms to evaluate by using the interpreter and
only 3ms using the compiled version of the expression.


[[expressions-compiler-configuration]]
=== Compiler Configuration

The compiler is not turned on by default, but you can turn it on in either of two
different ways. You can turn it on by using the parser configuration process
(xref:core/expressions/evaluation.adoc#expressions-parser-configuration[discussed
earlier]) or by using a Spring property when SpEL usage is embedded inside another
component. This section discusses both of these options.

The compiler can operate in one of three modes, which are captured in the
`org.springframework.expression.spel.SpelCompilerMode` enum. The modes are as follows.

* `OFF` (default): The compiler is switched off.
* `IMMEDIATE`: In immediate mode, the expressions are compiled as soon as possible. This
  is typically after the first interpreted evaluation. If the compiled expression fails
  (typically due to a type changing, as described earlier), the caller of the expression
  evaluation receives an exception.
* `MIXED`: In mixed mode, the expressions silently switch between interpreted and
  compiled mode over time. After some number of interpreted runs, they switch to compiled
  form and, if something goes wrong with the compiled form (such as a type changing, as
  described earlier), the expression automatically switches back to interpreted form
  again. Sometime later, it may generate another compiled form and switch to it.
  Basically, the exception that the user gets in `IMMEDIATE` mode is instead handled
  internally.

`IMMEDIATE` mode exists because `MIXED` mode could cause issues for expressions that
have side effects. If a compiled expression blows up after partially succeeding, it
may have already done something that has affected the state of the system. If this
has happened, the caller may not want it to silently re-run in interpreted mode,
since part of the expression may be run twice.

After selecting a mode, use the `SpelParserConfiguration` to configure the parser. The
following example shows how to do so.

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	SpelParserConfiguration config = new SpelParserConfiguration(SpelCompilerMode.IMMEDIATE,
			this.getClass().getClassLoader());

	SpelExpressionParser parser = new SpelExpressionParser(config);

	Expression expr = parser.parseExpression("payload");

	MyMessage message = new MyMessage();

	Object payload = expr.getValue(message);
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	val config = SpelParserConfiguration(SpelCompilerMode.IMMEDIATE,
			this.javaClass.classLoader)

	val parser = SpelExpressionParser(config)

	val expr = parser.parseExpression("payload")

	val message = MyMessage()

	val payload = expr.getValue(message)
----
======

When you specify the compiler mode, you can also specify a `ClassLoader` (passing `null`
is allowed). Compiled expressions are defined in a child `ClassLoader` created under any
that is supplied. It is important to ensure that, if a `ClassLoader` is specified, it can
see all the types involved in the expression evaluation process. If you do not specify a
`ClassLoader`, a default `ClassLoader` is used (typically the context `ClassLoader` for
the thread that is running during expression evaluation).

The second way to configure the compiler is for use when SpEL is embedded inside some
other component and it may not be possible to configure it through a configuration
object. In such cases, it is possible to set the `spring.expression.compiler.mode`
property via a JVM system property (or via the
xref:appendix.adoc#appendix-spring-properties[`SpringProperties`] mechanism) to one of the
`SpelCompilerMode` enum values (`off`, `immediate`, or `mixed`).


[[expressions-compiler-limitations]]
=== Compiler Limitations

Spring does not support compiling every kind of expression. The primary focus is on
common expressions that are likely to be used in performance-critical contexts. The
following kinds of expressions cannot be compiled.

* Expressions involving assignment
* Expressions relying on the conversion service
* Expressions using custom resolvers
* Expressions using overloaded operators
* Expressions using array construction syntax
* Expressions using selection or projection

Compilation of additional kinds of expressions may be supported in the future.

