[[spring-testing-annotation-contextconfiguration]]
= `@ContextConfiguration`

* attributes
    ** `locations`
        *** Check API
        *** typically, they are
            **** .xml -- `GenericXmlContextLoader` --
            **** Groovy scripts | class path -- `GenericGroovyXmlContextLoader` --
    ** `classes`
        *** Check API
        *** typically, they are
            **** `@Configuration` classes ->
                ***** `@Component` classes
                ***** `@Service` classes
                ***** ...
            **** Check xref:testing/testcontext-framework/ctx-management/javaconfig.adoc#testcontext-ctx-management-javaconfig-component-classes[Component Classes]
    ** `initializers`
        *** Check API
    ** `inheritLocations` & `inheritInitializers`
        *** Check API
* use cases
    ** | test class
        *** allows configuring metadata -- to determine, for integration tests, how to --
            **** load an `ApplicationContext`
            **** configure an `ApplicationContext`

* _Example1:_

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	@ContextConfiguration("/test-config.xml") // <1>
	class XmlApplicationContextTests {
		// class body...
	}
----
<1> Referring to an XML file.

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	@ContextConfiguration("/test-config.xml") // <1>
	class XmlApplicationContextTests {
		// class body...
	}
----
<1> Referring to an XML file.
======

* _Example2:_ `@ContextConfiguration` / `classes` specified

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	@ContextConfiguration(classes = TestConfig.class) // <1>
	class ConfigClassApplicationContextTests {
		// class body...
	}
----
<1> Referring to a class.

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	@ContextConfiguration(classes = [TestConfig::class]) // <1>
	class ConfigClassApplicationContextTests {
		// class body...
	}
----
<1> Referring to a class.
======

* _Example3:_ `@ContextConfiguration` / `ApplicationContextInitializer` specified

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	@ContextConfiguration(initializers = CustomContextInitializer.class) // <1>
	class ContextInitializerTests {
		// class body...
	}
----
<1> Declaring an initializer class.

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	@ContextConfiguration(initializers = [CustomContextInitializer::class]) // <1>
	class ContextInitializerTests {
		// class body...
	}
----
<1> Declaring an initializer class.
======

* _Example4:_ `@ContextConfiguration` / `ContextLoader` and `locations` specified

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	@ContextConfiguration(locations = "/test-context.xml", loader = CustomContextLoader.class) // <1>
	class CustomLoaderXmlApplicationContextTests {
		// class body...
	}
----
<1> Configuring both a location and a custom loader.

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	@ContextConfiguration("/test-context.xml", loader = CustomContextLoader::class) // <1>
	class CustomLoaderXmlApplicationContextTests {
		// class body...
	}
----
<1> Configuring both a location and a custom loader.
======

* Check
    ** xref:testing/testcontext-framework/ctx-management.adoc[Context Management]
    ** xref:testing/testcontext-framework/support-classes.adoc#testcontext-junit-jupiter-nested-test-configuration[`@Nested` test class configuration]
