[[mockmvc-server-setup-options]]
= Setup Options

* ways to set up MockMvc
    ** point directly to the controllers & programmatically configure Spring MVC infrastructure
    ** point to Spring configuration / Spring MVC and controller infrastructure
* if you use `ApplicationContext` -> loads your actual Spring MVC configuration
* `WebApplicationContext`-based test -> loads your actual Spring MVC configuration
    ** == integration test
* TestContext framework caches the loaded Spring configuration -> helps keep tests running fast
* if you want to override services (Reason: 🧠focus on testing the web layer 🧠) / used by your controller
    ** == standalone test == unit test == 1 controller tested / time
        *** -> additional integration tests / verify Spring MVC configuration
    ** ways
        *** use `@MockitoBean`
        *** inject manually the controller with mock dependencies -> NOT necessary to load Spring configuration
            **** easier to see which controller is being tested
