[[beans-annotation-config]]
= Annotation-based Container Configuration

* Spring -- provides -- support for
    ** annotation-based configuration / operate | metadata | component class
        *** annotations ALLOWED |
            **** class,
            **** method
            **** field declaration
        *** `BeanPostProcessors` + annotations -> core IOC container -- is aware of -- specific annotations
            **** see xref:core/beans/factory-extension.adoc#beans-factory-extension-bpp-examples-aabpp[Example: The `AutowiredAnnotationBeanPostProcessor`]
        *** xref:core/beans/annotation-config/autowired.adoc[`@Autowired`] vs xref:core/beans/dependencies/factory-autowire.adoc[Autowiring Collaborators]
            **** SAME capabilities + MORE fine-grained control + WIDER applicability
    ** JSR-250 annotations
        *** _Example:_ `@PostConstruct` and `@PreDestroy`
    ** JSR-330 (Dependency Injection for Java) annotations / contained | `jakarta.inject` package
        *** _Example:_ `@Inject` and `@Named`
        *** see xref:core/beans/standard-annotations.adoc[relevant section]

* Annotation injection -- is performed BEFORE -- external property injection
    ** 👀-> if you use mixed approaches -> external configuration (_Example:_ XML-specified bean properties) overrides annotations for properties 👀

* post-processors -- can be registered as -- individual bean definitions
    ** ⚠️ BUT they are implicitly registered ALREADY | `AnnotationConfigApplicationContext` ⚠️

* `<context:annotation-config/>`
    ** requirements
        *** XML-based Spring setup
    ** enable mixing annotation-based configuration
    ** ONLY looks for annotations | SAME application context's beans
        *** _Example:_ if you put `<context:annotation-config/>` | `WebApplicationContext` -- for a -- xref:web/webmvc/mvc-servlet.adoc[`DispatcherServlet`] -> ONLY checks for `@Autowired` beans |
            **** your controllers
            **** ❌NOT your services ❌
    ** 👀IMPLICITLY registers the post-processors 👀
        *** {spring-framework-api}/context/annotation/ConfigurationClassPostProcessor.html[`ConfigurationClassPostProcessor`]
        *** {spring-framework-api}/beans/factory/annotation/AutowiredAnnotationBeanPostProcessor.html[`AutowiredAnnotationBeanPostProcessor`]
        *** {spring-framework-api}/context/annotation/CommonAnnotationBeanPostProcessor.html[`CommonAnnotationBeanPostProcessor`]
        *** {spring-framework-api}/orm/jpa/support/PersistenceAnnotationBeanPostProcessor.html[`PersistenceAnnotationBeanPostProcessor`]
        *** {spring-framework-api}/context/event/EventListenerMethodProcessor.html[`EventListenerMethodProcessor`]
    ** _Example:_
+
[source,xml,indent=0,subs="verbatim,quotes"]
----
	<?xml version="1.0" encoding="UTF-8"?>
	<beans xmlns="http://www.springframework.org/schema/beans"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns:context="http://www.springframework.org/schema/context"
		xsi:schemaLocation="http://www.springframework.org/schema/beans
			https://www.springframework.org/schema/beans/spring-beans.xsd
			http://www.springframework.org/schema/context
			https://www.springframework.org/schema/context/spring-context.xsd">

		<context:annotation-config/>

	</beans>
----
