[[beans-definition]]
= Bean Overview

* := actual objects / make up your application
  ** -- managed by -- Spring IoC container
  ** `BeanDefinition` object
    *** == representation of the bean | container / contains the metadata
      **** package-qualified class name
        ***** implementation class of the bean / being defined
      **** behavioral configuration elements / states how the bean should behave in the container
        ***** _Example:_ scope, lifecycle callbacks
      **** collaborators or dependencies
        ***** == -- references to -- other beans
      **** other configuration settings
        ***** _Example:_ size limit of the pool or number of connections to use in a bean / manages a connection pool
    *** metadata -- related to -- properties
* ways to create a bean
  ** configuration metadata / supplied to the container
    *** ways
      **** XML `<bean/>` definitions
      **** `@Bean`
  ** create objects / outside the container & register them | `ApplicationContext` implementations
    *** steps
      **** `ApplicationContext.getBeanFactory()` returns `DefaultListableBeanFactory` implementation
      **** `DefaultListableBeanFactory.registerSingleton(..)` or `DefaultListableBeanFactory.registerBeanDefinition(..)`
    *** NOT common
  ** bean definition metadata

[[beans-factory-bean-definition-tbl]]
.The bean definition
|===
| Property| Explained in...

| Class
| xref:core/beans/definition.adoc#beans-factory-class[Instantiating Beans]

| Name
| xref:core/beans/definition.adoc#beans-beanname[Naming Beans]

| Scope
| xref:core/beans/factory-scopes.adoc[Bean Scopes]

| Constructor arguments
| xref:core/beans/dependencies/factory-collaborators.adoc[Dependency Injection]

| Properties
| xref:core/beans/dependencies/factory-collaborators.adoc[Dependency Injection]

| Autowiring mode
| xref:core/beans/dependencies/factory-autowire.adoc[Autowiring Collaborators]

| Lazy initialization mode
| xref:core/beans/dependencies/factory-lazy-init.adoc[Lazy-initialized Beans]

| Initialization method
| xref:core/beans/factory-nature.adoc#beans-factory-lifecycle-initializingbean[Initialization Callbacks]

| Destruction method
| xref:core/beans/factory-nature.adoc#beans-factory-lifecycle-disposablebean[Destruction Callbacks]
|===

* Bean metadata and manually supplied singleton instances -- need to be registered -- as early as possible
  ** Reason: 🧠 container can properly reason about them | autowiring and other introspection steps 🧠
* overriding existing metadata and existing singleton instances -- is supported to -- some degree
* registration of new beans | runtime ( / -- concurrently with -- live access to the factory)
  ** NOT officially supported
  ** -- may lead to --
    *** concurrent access exceptions,
    *** inconsistent state in the bean container


[[beans-definition-overriding]]
== Overriding Beans

* == register a bean / used identifier ALREADY allocated
  ** -> configuration harder to read
  ** container logs (by default) every attempt to override a bean at `INFO` level
    *** if you set `allowBeanDefinitionOverriding=true` -> those logs are silenced
* ⚠️will be deprecated in a future release ⚠️
* `allowBeanDefinitionOverriding=false` | `ApplicationContext`
  ** disable bean overriding
    *** if you try to override bean | this situation -> exception is thrown

* priority from higher to lower
  ** `@Bean` factory method
  ** bean class' pre-declared constructor

* override beans | test scenarios
  ** 👀convenient👀
  ** explicit support | Spring Framework v6.2+
    *** see xref:testing/testcontext-framework/bean-overriding.adoc[this section]

[[beans-beanname]]
== Naming Beans

* 💡>=1 identifiers / EVERY bean 💡
  ** requirements
    *** 👀UNIQUE | container / hosts the bean 👀
  ** use cases
    *** NORMALLY, 1!
    *** if it requires >1 -> extra ones == aliases
  ** ways to specify them
    *** | XML-based configuration metadata,
      **** `id` attribute,
      **** `name` attribute,
        ***** ALLOWED, alphanumeric & special characters
        ***** MOST common pattern is alphanumeric
        ***** if specify > 1 -> you can separate them by
          ****** `,`
          ****** `;`
          ****** ` ` == white space
      **** `id` & `name`
    *** ❌`name` or an `id`, NOT required to supply ❌
      **** if you do NOT supply it -> container -- generates a -- UNIQUE name / that bean
        ***** use cases
          ******  xref:core/beans/dependencies/factory-properties-detailed.adoc#beans-inner-beans[inner beans]
          ****** xref:core/beans/dependencies/factory-autowire.adoc[autowiring collaborators]
        ***** ❌NOT can be used |
          ****** `ref` element or
          ****** Service Locator style lookup ❌
        ***** PREVIOUS == you must provide a name

* conventions
  ** if you name beans -> use the standard Java convention for instance field names ==
    *** start with a lowercase letter
    *** from first letter, camel-cased
  ** _Examples:_ `accountManager`, `accountService`, `userDao`, `loginController`
  ** benefits
    *** easier to read and understand
    *** if you use Spring AOP -> helps applying advice | set of beans / related by name.

* | component scanning the classpath, Spring -- generates -- bean names | unnamed
components /
  ** PREVIOUS rules + EXTRA rule
    *** ⚠️EXTRA rule ⚠️
      **** if there is >1 character & first and second characters are upper case,
 -> original casing gets preserved
    *** == rules | `java.beans.Introspector.decapitalize`

[[beans-beanname-alias]]
=== Aliasing a Bean / OUTSIDE the Bean Definition

* if you provide >1 `name` -> use cases
  ** COMMON dependency | SEVERAL components /
    *** allows referring specifically / EACH one

* ❌specify ALL aliases | bean is actually defined, NOT always adequate ❌
  ** recommendation
    *** 👀introduce an alias | bean / defined elsewhere 👀
      **** | In XML-based configuration metadata, use the `<alias/>` element
+
[source,xml,indent=0,subs="verbatim,quotes"]
----
	<alias name="fromName" alias="toName"/>
    <!--  bean | SAME container / named `fromName`, once it's referred by `fromName` -> be referred as `toName` -->
----

  ** _Example:_ large systems /
    *** configuration is split | EACH subsystem
    *** OWN set of object definitions / EACH subsystem


* TODO:

For example, the configuration metadata for subsystem A may refer to a DataSource by the name of `subsystemA-dataSource`.
The configuration metadata for subsystem B may refer to a DataSource by the name of `subsystemB-dataSource`.
When composing the main application that uses both these subsystems, the main application refers to the DataSource by the name of `myApp-dataSource`.
To have all three names refer to the same object, you can add the following alias definitions to the configuration metadata:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<alias name="myApp-dataSource" alias="subsystemA-dataSource"/>
	<alias name="myApp-dataSource" alias="subsystemB-dataSource"/>
----

Now each component and the main application can refer to the dataSource through a name that is unique and guaranteed not to clash with any other definition (effectively creating a namespace), yet they refer to the same bean.

.Java-configuration
****
If you use Java Configuration, the `@Bean` annotation can be used to provide aliases.
See xref:core/beans/java/bean-annotation.adoc[Using the `@Bean` Annotation] for details.
****


[[beans-factory-class]]
== Instantiating Beans

* bean definition
  ** ==
A bean definition is essentially a recipe for creating one or more objects.
The container looks at the recipe for a named bean when asked and uses the configuration metadata encapsulated by that bean definition to create (or acquire) an actual object.

If you use XML-based configuration metadata, you specify the type (or class) of object
that is to be instantiated in the `class` attribute of the `<bean/>` element. This
`class` attribute (which, internally, is a `Class` property on a `BeanDefinition`
instance) is usually mandatory. (For exceptions, see
xref:core/beans/definition.adoc#beans-factory-class-instance-factory-method[Instantiation by Using an Instance Factory Method] and xref:core/beans/child-bean-definitions.adoc[Bean Definition Inheritance].)
You can use the `Class` property in one of two ways:

* Typically, to specify the bean class to be constructed in the case where the container
  itself directly creates the bean by calling its constructor reflectively, somewhat
  equivalent to Java code with the `new` operator.
* To specify the actual class containing the `static` factory method that is
  invoked to create the object, in the less common case where the container invokes a
  `static` factory method on a class to create the bean. The object type returned
  from the invocation of the `static` factory method may be the same class or another
  class entirely.

.Nested class names
****
If you want to configure a bean definition for a nested class, you may use either the
binary name or the source name of the nested class.

For example, if you have a class called `SomeThing` in the `com.example` package, and
this `SomeThing` class has a `static` nested class called `OtherThing`, they can be
separated by a dollar sign (`$`) or a dot (`.`). So the value of the `class` attribute in
a bean definition would be `com.example.SomeThing$OtherThing` or
`com.example.SomeThing.OtherThing`.
****


[[beans-factory-class-ctor]]
=== Instantiation with a Constructor

When you create a bean by the constructor approach, all normal classes are usable by and
compatible with Spring. That is, the class being developed does not need to implement
any specific interfaces or to be coded in a specific fashion. Simply specifying the bean
class should suffice. However, depending on what type of IoC you use for that specific
bean, you may need a default (empty) constructor.

The Spring IoC container can manage virtually any class you want it to manage. It is
not limited to managing true JavaBeans. Most Spring users prefer actual JavaBeans with
only a default (no-argument) constructor and appropriate setters and getters modeled
after the properties in the container. You can also have more exotic non-bean-style
classes in your container. If, for example, you need to use a legacy connection pool
that absolutely does not adhere to the JavaBean specification, Spring can manage it as
well.

With XML-based configuration metadata you can specify your bean class as follows:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<bean id="exampleBean" class="examples.ExampleBean"/>

	<bean name="anotherExample" class="examples.ExampleBeanTwo"/>
----

For details about the mechanism for supplying arguments to the constructor (if required)
and setting object instance properties after the object is constructed, see
xref:core/beans/dependencies/factory-collaborators.adoc[Injecting Dependencies].

NOTE: In the case of constructor arguments, the container can select a corresponding
constructor among several overloaded constructors. That said, to avoid ambiguities,
it is recommended to keep your constructor signatures as straightforward as possible.


[[beans-factory-class-static-factory-method]]
=== Instantiation with a Static Factory Method

When defining a bean that you create with a static factory method, use the `class`
attribute to specify the class that contains the `static` factory method and an attribute
named `factory-method` to specify the name of the factory method itself. You should be
able to call this method (with optional arguments, as described later) and return a live
object, which subsequently is treated as if it had been created through a constructor.
One use for such a bean definition is to call `static` factories in legacy code.

The following bean definition specifies that the bean will be created by calling a
factory method. The definition does not specify the type (class) of the returned object,
but rather the class containing the factory method. In this example, the
`createInstance()` method must be a `static` method. The following example shows how to
specify a factory method:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<bean id="clientService"
		class="examples.ClientService"
		factory-method="createInstance"/>
----

The following example shows a class that would work with the preceding bean definition:

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	public class ClientService {
		private static ClientService clientService = new ClientService();
		private ClientService() {}

		public static ClientService createInstance() {
			return clientService;
		}
	}
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	class ClientService private constructor() {
		companion object {
			private val clientService = ClientService()
			@JvmStatic
			fun createInstance() = clientService
		}
	}
----
======

For details about the mechanism for supplying (optional) arguments to the factory method
and setting object instance properties after the object is returned from the factory,
see xref:core/beans/dependencies/factory-properties-detailed.adoc[Dependencies and Configuration in Detail].

NOTE: In the case of factory method arguments, the container can select a corresponding
method among several overloaded methods of the same name. That said, to avoid ambiguities,
it is recommended to keep your factory method signatures as straightforward as possible.

[TIP]
====
A typical problematic case with factory method overloading is Mockito with its many
overloads of the `mock` method. Choose the most specific variant of `mock` possible:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<bean id="clientService" class="org.mockito.Mockito" factory-method="mock">
		<constructor-arg type="java.lang.Class" value="examples.ClientService"/>
		<constructor-arg type="java.lang.String" value="clientService"/>
	</bean>
----
====


[[beans-factory-class-instance-factory-method]]
=== Instantiation by Using an Instance Factory Method

Similar to instantiation through a xref:core/beans/definition.adoc#beans-factory-class-static-factory-method[static factory method]
, instantiation with an instance factory method invokes a non-static
method of an existing bean from the container to create a new bean. To use this
mechanism, leave the `class` attribute empty and, in the `factory-bean` attribute,
specify the name of a bean in the current (or parent or ancestor) container that contains
the instance method that is to be invoked to create the object. Set the name of the
factory method itself with the `factory-method` attribute. The following example shows
how to configure such a bean:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<!-- the factory bean, which contains a method called createClientServiceInstance() -->
	<bean id="serviceLocator" class="examples.DefaultServiceLocator">
		<!-- inject any dependencies required by this locator bean -->
	</bean>

	<!-- the bean to be created via the factory bean -->
	<bean id="clientService"
		factory-bean="serviceLocator"
		factory-method="createClientServiceInstance"/>
----

The following example shows the corresponding class:

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	public class DefaultServiceLocator {

		private static ClientService clientService = new ClientServiceImpl();

		public ClientService createClientServiceInstance() {
			return clientService;
		}
	}
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	class DefaultServiceLocator {
		companion object {
			private val clientService = ClientServiceImpl()
		}
		fun createClientServiceInstance(): ClientService {
			return clientService
		}
	}
----
======

One factory class can also hold more than one factory method, as the following example shows:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<bean id="serviceLocator" class="examples.DefaultServiceLocator">
		<!-- inject any dependencies required by this locator bean -->
	</bean>

	<bean id="clientService"
		factory-bean="serviceLocator"
		factory-method="createClientServiceInstance"/>

	<bean id="accountService"
		factory-bean="serviceLocator"
		factory-method="createAccountServiceInstance"/>
----

The following example shows the corresponding class:

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	public class DefaultServiceLocator {

		private static ClientService clientService = new ClientServiceImpl();

		private static AccountService accountService = new AccountServiceImpl();

		public ClientService createClientServiceInstance() {
			return clientService;
		}

		public AccountService createAccountServiceInstance() {
			return accountService;
		}
	}
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	class DefaultServiceLocator {
		companion object {
			private val clientService = ClientServiceImpl()
			private val accountService = AccountServiceImpl()
		}

		fun createClientServiceInstance(): ClientService {
			return clientService
		}

		fun createAccountServiceInstance(): AccountService {
			return accountService
		}
	}
----
======

This approach shows that the factory bean itself can be managed and configured through
dependency injection (DI).
See xref:core/beans/dependencies/factory-properties-detailed.adoc[Dependencies and Configuration in Detail].

NOTE: In Spring documentation, "factory bean" refers to a bean that is configured in the
Spring container and that creates objects through an
xref:core/beans/definition.adoc#beans-factory-class-instance-factory-method[instance] or
xref:core/beans/definition.adoc#beans-factory-class-static-factory-method[static] factory method. By contrast,
`FactoryBean` (notice the capitalization) refers to a Spring-specific
xref:core/beans/factory-extension.adoc#beans-factory-extension-factorybean[`FactoryBean`] implementation class.


[[beans-factory-type-determination]]
=== Determining a Bean's Runtime Type

The runtime type of a specific bean is non-trivial to determine. A specified class in
the bean metadata definition is just an initial class reference, potentially combined
with a declared factory method or being a `FactoryBean` class which may lead to a
different runtime type of the bean, or not being set at all in case of an instance-level
factory method (which is resolved via the specified `factory-bean` name instead).
Additionally, AOP proxying may wrap a bean instance with an interface-based proxy with
limited exposure of the target bean's actual type (just its implemented interfaces).

The recommended way to find out about the actual runtime type of a particular bean is
a `BeanFactory.getType` call for the specified bean name. This takes all of the above
cases into account and returns the type of object that a `BeanFactory.getBean` call is
going to return for the same bean name.


